import Foundation

// Omarchy's own themes (basecamp/omarchy `themes/*/colors.toml`), keys taken as-is.
// Generated by scripts/generate-builtin-themes.py — edit the script, not this file.
extension BuiltInThemes {
    static let omarchy: [ThemeDefinition] = [
        ethereal,
        hackerman,
        lastHorizon,
        lumon,
        lupine,
        matteBlack,
        miasma,
        osakaJade,
        retro82,
        ristretto,
        solitude,
        vantablack,
        white,
    ]

    static let ethereal = ThemeDefinition(
        name: "Ethereal",
        mode: .dark,
        colors: [
            "accent": "#7d82d9", "background": "#060b1e", "blue": "#7d82d9", "bright_blue": "#c2c4f0",
            "bright_cyan": "#dfeaf0", "bright_foreground": "#ffcead", "bright_green": "#c4cfc4",
            "bright_magenta": "#ead7e7", "bright_red": "#faaaa9", "bright_yellow": "#f7dc9c", "brown": "#75452a",
            "cyan": "#a3bfd1", "dark_background": "#040816", "dark_foreground": "#6d7db6",
            "darker_background": "#030610", "foreground": "#ffcead", "green": "#92a593",
            "light_foreground": "#c9b8a6", "lighter_background": "#131a3a", "magenta": "#c89dc1",
            "muted": "#6d7db6", "orange": "#eb8b54", "red": "#ed5b5a", "selection_background": "#252e56",
            "yellow": "#e9bb4f",
        ],
        icon: "sparkles",
        keywords: ["omarchy", "ethereal"]
    )

    static let hackerman = ThemeDefinition(
        name: "Hackerman",
        mode: .dark,
        colors: [
            "accent": "#82fb9c", "background": "#0b0c16", "blue": "#829dd4", "bright_blue": "#c4d2ed",
            "bright_cyan": "#d1fffe", "bright_foreground": "#ddf7ff", "bright_green": "#9cf7c2",
            "bright_magenta": "#cddbf4", "bright_red": "#85ff9d", "bright_yellow": "#a4ffec", "brown": "#287b51",
            "cyan": "#7cf8f7", "dark_background": "#080910", "dark_foreground": "#6a6e95",
            "darker_background": "#06060c", "foreground": "#ddf7ff", "green": "#4fe88f",
            "light_foreground": "#b5c5db", "lighter_background": "#151828", "magenta": "#86a7df",
            "muted": "#2d3450", "orange": "#50f7a3", "red": "#50f872", "selection_background": "#1f253a",
            "yellow": "#50f7d4",
        ],
        icon: "terminal",
        keywords: ["omarchy", "hackerman"]
    )

    static let lastHorizon = ThemeDefinition(
        name: "Last Horizon",
        mode: .dark,
        colors: [
            "accent": "#b59790", "background": "#0c0b0c", "blue": "#b59790", "bright_blue": "#b59790",
            "bright_cyan": "#a5a0b6", "bright_foreground": "#e2dddc", "bright_green": "#87a9b0",
            "bright_magenta": "#c4d8e2", "bright_red": "#c38b7b", "bright_yellow": "#6b5e73", "cyan": "#a5a0b6",
            "dark_background": "#090809", "dark_foreground": "#584e51", "darker_background": "#060606",
            "foreground": "#fafcfb", "green": "#87a9b0", "light_foreground": "#cfd3cd",
            "lighter_background": "#0c0b0c", "magenta": "#c4d8e2", "muted": "#584e51", "red": "#c38b7b",
            "selection_background": "#584e51", "yellow": "#6b5e73",
        ],
        icon: "sunset",
        keywords: ["omarchy", "lasthorizon"]
    )

    static let lumon = ThemeDefinition(
        name: "Lumon",
        mode: .dark,
        colors: [
            "accent": "#8bc9eb", "background": "#16242d", "blue": "#6fb8e3", "bright_blue": "#f2fcff",
            "bright_cyan": "#d1eef8", "bright_foreground": "#f2fcff", "bright_green": "#86b7d8",
            "bright_magenta": "#b1d8ee", "bright_red": "#73a6cb", "bright_yellow": "#9dcae5", "brown": "#456475",
            "cyan": "#b4e4f6", "dark_background": "#101b21", "dark_foreground": "#4d86b0",
            "darker_background": "#0b1216", "foreground": "#d6e2ee", "green": "#5e95bc",
            "light_foreground": "#d6e2ee", "lighter_background": "#1b2d40", "magenta": "#8bc9eb",
            "muted": "#304860", "orange": "#8bc9eb", "red": "#4d86b0", "selection_background": "#243d56",
            "yellow": "#6fa4c9",
        ],
        icon: "building.columns",
        keywords: ["omarchy", "lumon"]
    )

    static let lupine = ThemeDefinition(
        name: "Lupine",
        mode: .light,
        colors: [
            "accent": "#3264eb", "background": "#fafafa", "blue": "#3264eb", "bright_blue": "#5482ff",
            "bright_cyan": "#3986ff", "bright_foreground": "#000000", "bright_green": "#9f85e0",
            "bright_magenta": "#b363ff", "bright_red": "#f930fb", "bright_yellow": "#358fff", "brown": "#013a6f",
            "cyan": "#0c67de", "dark_background": "#ececec", "dark_foreground": "#757575",
            "darker_background": "#dedede", "foreground": "#212121", "green": "#4a2fd0",
            "light_foreground": "#424242", "lighter_background": "#f5f5f5", "magenta": "#8a4ad7",
            "muted": "#9e9e9e", "orange": "#026fde", "red": "#c900c4", "selection_background": "#d0d0d0",
            "yellow": "#026fde",
        ],
        icon: "drop.fill",
        keywords: ["omarchy", "lupine"]
    )

    static let matteBlack = ThemeDefinition(
        name: "Matte Black",
        mode: .dark,
        colors: [
            "accent": "#e68e0d", "background": "#121212", "blue": "#e68e0d", "bright_blue": "#f59e0b",
            "bright_cyan": "#eaeaea", "bright_foreground": "#bebebe", "bright_green": "#ffc107",
            "bright_magenta": "#b91c1c", "bright_red": "#b91c1c", "bright_yellow": "#b90a0a", "brown": "#631e1e",
            "cyan": "#bebebe", "dark_background": "#0d0d0d", "dark_foreground": "#555555",
            "darker_background": "#090909", "foreground": "#bebebe", "green": "#ffc107",
            "light_foreground": "#8a8a8d", "lighter_background": "#1e1e1e", "magenta": "#d35f5f",
            "muted": "#333333", "orange": "#c63d3d", "red": "#d35f5f", "selection_background": "#2a2a2a",
            "yellow": "#b91c1c",
        ],
        icon: "circle.fill",
        keywords: ["omarchy", "matteblack"]
    )

    static let miasma = ThemeDefinition(
        name: "Miasma",
        mode: .dark,
        colors: [
            "accent": "#78824b", "background": "#222222", "blue": "#78824b", "bright_blue": "#78824b",
            "bright_cyan": "#c9a554", "bright_foreground": "#c2c2b0", "bright_green": "#5f875f",
            "bright_magenta": "#bb7744", "bright_red": "#685742", "bright_yellow": "#b36d43", "brown": "#463121",
            "cyan": "#c9a554", "dark_background": "#191919", "dark_foreground": "#555555",
            "darker_background": "#121212", "foreground": "#c2c2b0", "green": "#5f875f",
            "light_foreground": "#8a8a7e", "lighter_background": "#2c2c2c", "magenta": "#bb7744",
            "muted": "#666666", "orange": "#8d6242", "red": "#685742", "selection_background": "#383838",
            "yellow": "#b36d43",
        ],
        icon: "smoke",
        keywords: ["omarchy", "miasma"]
    )

    static let osakaJade = ThemeDefinition(
        name: "Osaka Jade",
        mode: .dark,
        colors: [
            "accent": "#509475", "background": "#111c18", "blue": "#509475", "bright_blue": "#acd4cf",
            "bright_cyan": "#8cd3cb", "bright_foreground": "#f7e8b2", "bright_green": "#63b07a",
            "bright_magenta": "#75bbb3", "bright_red": "#db9f9c", "bright_yellow": "#e5c736", "brown": "#513925",
            "cyan": "#2dd5b7", "dark_background": "#0c1512", "dark_foreground": "#81b8a8",
            "darker_background": "#090f0d", "foreground": "#c1c497", "green": "#549e6a",
            "light_foreground": "#d6d5bc", "lighter_background": "#23372b", "magenta": "#d2689c",
            "muted": "#53685b", "orange": "#a2734b", "red": "#ff5345", "selection_background": "#32473b",
            "yellow": "#459451",
        ],
        icon: "diamond",
        keywords: ["omarchy", "osakajade"]
    )

    static let retro82 = ThemeDefinition(
        name: "Retro 82",
        mode: .dark,
        colors: [
            "accent": "#faa968", "background": "#05182e", "blue": "#3f8f8a", "bright_blue": "#faa968",
            "bright_cyan": "#8cbfb8", "bright_foreground": "#f6dcac", "bright_green": "#028391",
            "bright_magenta": "#3f8f8a", "bright_red": "#f85525", "bright_yellow": "#e97b3c", "brown": "#743d1e",
            "cyan": "#8cbfb8", "dark_background": "#031222", "dark_foreground": "#3f8f8a",
            "darker_background": "#020c17", "foreground": "#f6dcac", "green": "#028391",
            "light_foreground": "#a7c9c6", "lighter_background": "#0a2540", "magenta": "#3f8f8a",
            "muted": "#2a6b78", "orange": "#faa968", "red": "#f85525", "selection_background": "#134e5a",
            "yellow": "#e97b3c",
        ],
        icon: "tv",
        keywords: ["omarchy", "retro82"]
    )

    static let ristretto = ThemeDefinition(
        name: "Ristretto",
        mode: .dark,
        colors: [
            "accent": "#f38d70", "background": "#2c2525", "blue": "#f38d70", "bright_blue": "#f8a788",
            "bright_cyan": "#9bf1e1", "bright_foreground": "#e6d9db", "bright_green": "#c8e292",
            "bright_magenta": "#bebffd", "bright_red": "#ff8297", "bright_yellow": "#fcd675", "brown": "#7d4d3b",
            "cyan": "#85dacc", "dark_background": "#211b1b", "dark_foreground": "#72696a",
            "darker_background": "#181414", "foreground": "#e6d9db", "green": "#adda78",
            "light_foreground": "#c3b7b8", "lighter_background": "#3d2f2a", "magenta": "#a8a9eb",
            "muted": "#72696a", "orange": "#fb9a77", "red": "#fd6883", "selection_background": "#403e41",
            "yellow": "#f9cc6c",
        ],
        icon: "takeoutbag.and.cup.and.straw",
        keywords: ["omarchy", "ristretto"]
    )

    static let solitude = ThemeDefinition(
        name: "Solitude",
        mode: .dark,
        colors: [
            "accent": "#798186", "background": "#101315", "blue": "#798186", "bright_blue": "#5d6367",
            "bright_cyan": "#707070", "bright_foreground": "#a5aeb4", "bright_green": "#343d41",
            "bright_magenta": "#9a9a9a", "bright_red": "#de6145", "bright_yellow": "#c9c2b4", "cyan": "#707070",
            "dark_background": "#0c0e10", "dark_foreground": "#4b4e55", "darker_background": "#080a0b",
            "foreground": "#cacccc", "green": "#9fa5a9", "light_foreground": "#cbc2be",
            "lighter_background": "#101315", "magenta": "#aeaeae", "muted": "#4b4e55", "red": "#565d60",
            "selection_background": "#343d41", "yellow": "#d9dbdc",
        ],
        icon: "moon.zzz",
        keywords: ["omarchy", "solitude"]
    )

    static let vantablack = ThemeDefinition(
        name: "Vantablack",
        mode: .dark,
        colors: [
            "accent": "#8d8d8d", "background": "#000000", "blue": "#8d8d8d", "bright_blue": "#8d8d8d",
            "bright_cyan": "#b0b0b0", "bright_foreground": "#ffffff", "bright_green": "#b6b6b6",
            "bright_magenta": "#9b9b9b", "bright_red": "#a4a4a4", "bright_yellow": "#cecece", "brown": "#5c5c5c",
            "cyan": "#b0b0b0", "dark_background": "#090909", "dark_foreground": "#505050",
            "darker_background": "#070707", "foreground": "#ffffff", "green": "#b6b6b6",
            "light_foreground": "#ececec", "lighter_background": "#1a1a1a", "magenta": "#9b9b9b",
            "muted": "#7a7a7a", "orange": "#b9b9b9", "red": "#a4a4a4", "selection_background": "#1a1a1a",
            "yellow": "#cecece",
        ],
        icon: "square.fill",
        keywords: ["omarchy", "vantablack"]
    )

    static let white = ThemeDefinition(
        name: "White",
        mode: .light,
        colors: [
            "accent": "#6e6e6e", "background": "#ffffff", "blue": "#1a1a1a", "bright_blue": "#1a1a1a",
            "bright_cyan": "#3e3e3e", "bright_foreground": "#000000", "bright_green": "#3a3a3a",
            "bright_magenta": "#2e2e2e", "bright_red": "#2a2a2a", "bright_yellow": "#4a4a4a", "cyan": "#3e3e3e",
            "dark_background": "#f5f5f5", "dark_foreground": "#c0c0c0", "darker_background": "#e8e8e8",
            "foreground": "#000000", "green": "#3a3a3a", "light_foreground": "#000000",
            "lighter_background": "#c0c0c0", "magenta": "#2e2e2e", "muted": "#808080", "red": "#2a2a2a",
            "selection_background": "#c0c0c0", "yellow": "#4a4a4a",
        ],
        icon: "circle",
        keywords: ["omarchy", "white"]
    )
}
