import Foundation

/// Ghostty: writes the palette as `~/.config/ghostty/themes/Vibeshed`, points the config's
/// `theme =` at it, and makes running Ghostties reload (SIGUSR2, see `GhosttyApp`), so
/// every open terminal retints live. `apps: { ghostty: "<theme>" }` selects one of
/// Ghostty's own themes instead (`ghostty +list-themes`).
struct GhosttyTarget: ThemeTarget {
    let id = ThemeTargetID.ghostty
    let displayName = "Ghostty"
    var supportsPreview: Bool {
        true
    }

    static let themeName = "Vibeshed"

    /// Colors a config file can set itself; Ghostty lets those override the theme's.
    static let colorKeys: Set<String> = [
        "background", "foreground", "palette", "cursor-color", "cursor-text",
        "selection-background", "selection-foreground",
    ]

    static var configDirectory: String {
        "\(CLITools.configHome)/ghostty"
    }

    static var themePath: String {
        "\(configDirectory)/themes/\(themeName)"
    }

    /// Ghostty's config files in the order it loads them; later files override earlier ones.
    static var configPaths: [String] {
        let appSupport = ThemeFiles.home
            .appendingPathComponent("Library/Application Support/\(GhosttyApp.bundleID)").path
        return [configDirectory, appSupport].flatMap { ["\($0)/config", "\($0)/config.ghostty"] }
    }

    /// Where the `theme` line goes when there's no config file at all.
    static var newConfigPath: String {
        "\(configDirectory)/config.ghostty"
    }

    func apply(_ request: ThemeApplyRequest) async -> ThemeTargetOutcome {
        guard GhosttyApp.isInstalled || ThemeFiles.exists(Self.configDirectory) else {
            return .skipped("not installed")
        }
        let override = request.override(.ghostty)
        if let override, !Self.themeExists(override) {
            return .failed("no Ghostty theme named '\(override)'")
        }
        do {
            if override == nil {
                try ThemeFiles.write(Self.themeFile(request.palette, themeName: request.theme.name), to: Self.themePath)
            }
            try Self.selectTheme(override ?? Self.themeName, paths: Self.configPaths, newFile: Self.newConfigPath)
        } catch {
            return .failed(error.localizedDescription)
        }
        let reload = GhosttyApp.reloadConfig()
        guard !request.isPreview else { return .applied() }

        var notes: [String] = []
        let overrides = Set(Self.configPaths.compactMap(ThemeFiles.read).flatMap(Self.colorOverrides(in:)))
        if !overrides.isEmpty {
            notes.append("the config sets \(overrides.sorted().joined(separator: ", ")), which override the theme")
        }
        if reload.outdated > 0 {
            notes.append("Ghostty before 1.2 can't reload on its own: press ⌘⇧, in it")
        }
        return .applied(note: notes.isEmpty ? nil : notes.joined(separator: "; "))
    }

    func snapshot(config _: ThemeConfig) async -> ThemeRestore? {
        let files = ThemeFiles.snapshot(Self.configPaths + [Self.themePath])
        return {
            await files()
            GhosttyApp.reloadConfig()
        }
    }

    // MARK: - Theme file

    static func themeFile(_ palette: ThemePalette, themeName: String) -> String {
        var lines = [
            "# Generated by Vibeshed from the \"\(themeName)\" theme — rewritten on every theme switch.",
            "background = \(palette.background.hex)",
            "foreground = \(palette.foreground.hex)",
            "cursor-color = \(palette.cursor.hex)",
            "cursor-text = \(palette.background.hex)",
            "selection-background = \(palette.selectionBackground.hex)",
            "selection-foreground = \(palette.selectionForeground.hex)",
        ]
        lines += palette.ansi.enumerated().map { "palette = \($0.offset)=\($0.element.hex)" }
        return lines.joined(separator: "\n") + "\n"
    }

    /// Whether Ghostty can resolve `name`: an absolute path, or a file in the user's or
    /// Ghostty's bundled themes folder. `light:…,dark:…` pairs are left to Ghostty.
    static func themeExists(_ name: String) -> Bool {
        if name.contains(":") { return true }
        if name.hasPrefix("/") { return ThemeFiles.exists(name) }
        var folders = ["\(configDirectory)/themes"]
        if let app = GhosttyApp.appURL {
            folders.append(app.appendingPathComponent("Contents/Resources/ghostty/themes").path)
        }
        return !name.contains("/") && folders.contains { ThemeFiles.exists("\($0)/\(name)") }
    }

    // MARK: - Config

    /// Points every `theme =` line in the existing config files at `theme`, so no file
    /// can override another; with none anywhere, appends one to the file Ghostty loads
    /// last, or creates `newFile` when there's no config at all.
    static func selectTheme(_ theme: String, paths: [String], newFile: String) throws {
        let existing = paths.filter(ThemeFiles.exists)
        var selected = false
        for path in existing {
            guard let text = ThemeFiles.read(path) else { throw ThemeTargetError.unreadable(path) }
            guard let updated = replacingTheme(theme, in: text) else { continue }
            try ThemeFiles.write(updated, to: path)
            selected = true
        }
        guard !selected else { return }
        let path = existing.last ?? newFile
        try ThemeFiles.write(appendingTheme(theme, to: ThemeFiles.read(path)), to: path)
    }

    /// `config` with each `theme = …` line pointing at `theme`, or nil when it has none.
    static func replacingTheme(_ theme: String, in config: String) -> String? {
        var lines = config.components(separatedBy: "\n")
        let indices = lines.indices.filter { key(of: lines[$0]) == "theme" }
        guard !indices.isEmpty else { return nil }
        for index in indices {
            lines[index] = "theme = \(theme)"
        }
        return lines.joined(separator: "\n")
    }

    static func appendingTheme(_ theme: String, to config: String?) -> String {
        guard let config, !config.isEmpty else { return "theme = \(theme)\n" }
        return config + (config.hasSuffix("\n") ? "" : "\n") + "theme = \(theme)\n"
    }

    /// The color keys `config` sets directly.
    static func colorOverrides(in config: String) -> [String] {
        config.components(separatedBy: "\n").compactMap(key(of:)).filter(colorKeys.contains)
    }

    /// The key of a `key = value` line; nil for comments and blank lines.
    private static func key(of line: String) -> String? {
        let trimmed = line.trimmingCharacters(in: .whitespaces)
        guard !trimmed.hasPrefix("#"), let equals = trimmed.firstIndex(of: "=") else { return nil }
        return trimmed[..<equals].trimmingCharacters(in: .whitespaces)
    }
}
