import Foundation

/// Builds a Neovim colorscheme (`colors/vibeshed.lua`) from a palette: the editor UI,
/// legacy syntax groups, Tree-sitter and LSP captures, diagnostics, diffs and the
/// `:terminal` palette. Syntax roles match the VS Code theme's, so code highlights the
/// same in both editors.
enum NeovimThemeBuilder {
    /// One `nvim_set_hl` call. `link` wins over every other field.
    struct Highlight: Equatable {
        let group: String
        var fg: String?
        var bg: String?
        var sp: String?
        var styles: [String] = []
        var link: String?

        var lua: String {
            if let link { return "hl(\"\(group)\", { link = \"\(link)\" })" }
            let fields = [("fg", fg), ("bg", bg), ("sp", sp)].compactMap { key, value in
                value.map { "\(key) = \"\($0)\"" }
            } + styles.map { "\($0) = true" }
            return "hl(\"\(group)\", { \(fields.joined(separator: ", ")) })"
        }
    }

    static func colorscheme(_ palette: ThemePalette, themeName: String) -> String {
        let lines = highlights(palette).map(\.lua)
        let terminal = palette.ansi.enumerated().map { "vim.g.terminal_color_\($0.offset) = \"\($0.element.hex)\"" }
        return header(themeName, mode: palette.mode) + """
        local hl = function(name, spec) vim.api.nvim_set_hl(0, name, spec) end

        \(lines.joined(separator: "\n"))

        \(terminal.joined(separator: "\n"))

        """
    }

    /// A colorscheme that loads one of the user's installed schemes under the Vibeshed name,
    /// for themes with `apps: { neovim: "<scheme>" }`. It stays `vibeshed` so running
    /// editors keep following theme switches.
    static func alias(_ scheme: String, mode: ThemeMode, themeName: String) -> String {
        header(themeName, mode: mode) + """
        local ok, err = pcall(vim.cmd.colorscheme, \(luaString(scheme)))
        if not ok then
          vim.notify("vibeshed: " .. tostring(err), vim.log.levels.WARN)
        end
        vim.g.colors_name = "\(NeovimTarget.schemeName)"

        """
    }

    /// A double-quoted Lua string literal; Lua short strings can't hold raw line breaks.
    static func luaString(_ text: String) -> String {
        let escaped = text.replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
            .replacingOccurrences(of: "\n", with: "\\n")
            .replacingOccurrences(of: "\r", with: "\\r")
        return "\"\(escaped)\""
    }

    private static func header(_ themeName: String, mode: ThemeMode) -> String {
        // A line break in the name would end the comment and turn the rest into Lua source.
        let name = themeName.components(separatedBy: .newlines).joined(separator: " ")
        return """
        -- Generated by Vibeshed from the "\(name)" theme — rewritten on every theme switch.
        vim.cmd("highlight clear")
        if vim.fn.exists("syntax_on") == 1 then vim.cmd("syntax reset") end
        if vim.o.background ~= "\(mode.rawValue)" then vim.o.background = "\(mode.rawValue)" end
        vim.g.colors_name = "\(NeovimTarget.schemeName)"

        """
    }

    static func highlights(_ palette: ThemePalette) -> [Highlight] {
        editor(palette) + syntax(palette) + treesitter(palette) + diagnostics(palette) + plugins
    }

    // MARK: - Groups

    private static func color(_ palette: ThemePalette, _ key: String) -> String {
        (palette[key] ?? palette.foreground).hex
    }

    private static func editor(_ palette: ThemePalette) -> [Highlight] {
        let bg = palette.background.hex, fg = palette.foreground.hex, muted = palette.muted.hex
        let panel = palette.darkBackground.hex, raised = palette.lighterBackground.hex
        let border = palette.background.mix(palette.foreground, 0.2).hex
        let accent = palette.accent.hex, selection = palette.selectionBackground.hex
        let tint = { (color: ThemeColor, amount: Double) in palette.background.mix(color, amount).hex }
        return [
            .init(group: "Normal", fg: fg, bg: bg), .init(group: "NormalNC", link: "Normal"),
            .init(group: "NormalFloat", fg: fg, bg: panel), .init(group: "FloatBorder", fg: border, bg: panel),
            .init(group: "FloatTitle", fg: accent, bg: panel, styles: ["bold"]),
            .init(group: "Cursor", fg: bg, bg: palette.cursor.hex), .init(group: "lCursor", link: "Cursor"),
            .init(group: "CursorIM", link: "Cursor"), .init(group: "TermCursor", link: "Cursor"),
            .init(group: "CursorLine", bg: raised), .init(group: "CursorColumn", link: "CursorLine"),
            .init(group: "ColorColumn", bg: raised),
            .init(group: "LineNr", fg: muted), .init(group: "CursorLineNr", fg: accent, styles: ["bold"]),
            .init(group: "SignColumn", fg: muted, bg: bg), .init(group: "FoldColumn", fg: muted, bg: bg),
            .init(group: "Folded", fg: muted, bg: raised),
            .init(group: "WinSeparator", fg: border), .init(group: "VertSplit", link: "WinSeparator"),
            .init(group: "StatusLine", fg: fg, bg: panel), .init(group: "StatusLineNC", fg: muted, bg: panel),
            .init(group: "TabLine", fg: muted, bg: panel), .init(group: "TabLineFill", bg: panel),
            .init(group: "TabLineSel", fg: fg, bg: bg, styles: ["bold"]),
            .init(group: "WinBar", fg: fg, styles: ["bold"]), .init(group: "WinBarNC", fg: muted),
            .init(group: "Pmenu", fg: fg, bg: panel),
            .init(group: "PmenuSel", fg: palette.selectionForeground.hex, bg: selection, styles: ["bold"]),
            .init(group: "PmenuSbar", bg: raised), .init(group: "PmenuThumb", bg: muted),
            .init(group: "PmenuMatch", fg: accent, styles: ["bold"]), .init(group: "WildMenu", link: "PmenuSel"),
            .init(group: "Visual", bg: selection), .init(group: "VisualNOS", link: "Visual"),
            .init(group: "Search", fg: bg, bg: palette.yellow.hex), .init(group: "IncSearch", fg: bg, bg: accent),
            .init(group: "CurSearch", link: "IncSearch"), .init(group: "Substitute", fg: bg, bg: palette.red.hex),
            .init(group: "MatchParen", fg: accent, bg: raised, styles: ["bold"]),
            .init(group: "NonText", fg: border), .init(group: "Whitespace", link: "NonText"),
            .init(group: "SpecialKey", link: "NonText"), .init(group: "EndOfBuffer", link: "NonText"),
            .init(group: "Conceal", fg: muted), .init(group: "Directory", fg: palette.blue.hex),
            .init(group: "Title", fg: accent, styles: ["bold"]), .init(group: "ErrorMsg", fg: palette.red.hex),
            .init(group: "WarningMsg", fg: palette.yellow.hex), .init(group: "ModeMsg", fg: fg, styles: ["bold"]),
            .init(group: "MoreMsg", fg: palette.green.hex), .init(group: "Question", fg: palette.green.hex),
            .init(group: "QuickFixLine", bg: selection),
            .init(group: "SpellBad", sp: palette.red.hex, styles: ["undercurl"]),
            .init(group: "SpellCap", sp: palette.yellow.hex, styles: ["undercurl"]),
            .init(group: "SpellLocal", sp: palette.cyan.hex, styles: ["undercurl"]),
            .init(group: "SpellRare", sp: palette.magenta.hex, styles: ["undercurl"]),
            .init(group: "DiffAdd", bg: tint(palette.green, 0.2)),
            .init(group: "DiffChange", bg: tint(palette.blue, 0.15)),
            .init(group: "DiffDelete", fg: palette.red.hex, bg: tint(palette.red, 0.15)),
            .init(group: "DiffText", bg: tint(palette.blue, 0.35)),
            .init(group: "Added", fg: palette.green.hex), .init(group: "Changed", fg: palette.blue.hex),
            .init(group: "Removed", fg: palette.red.hex),
        ]
    }

    private static func syntax(_ palette: ThemePalette) -> [Highlight] {
        let hex = { color(palette, $0) }
        let links = [
            ("Character", "String"), ("Float", "Number"), ("Conditional", "Statement"), ("Repeat", "Statement"),
            ("Label", "Statement"), ("Keyword", "Statement"), ("Exception", "Statement"), ("Include", "PreProc"),
            ("Define", "PreProc"), ("Macro", "PreProc"), ("PreCondit", "PreProc"), ("StorageClass", "Type"),
            ("Structure", "Type"), ("Typedef", "Type"),
        ]
        return [
            .init(group: "Comment", fg: hex("muted"), styles: ["italic"]),
            .init(group: "Constant", fg: hex("orange")), .init(group: "String", fg: hex("green")),
            .init(group: "Number", fg: hex("orange")), .init(group: "Boolean", fg: hex("orange")),
            .init(group: "Identifier", fg: hex("foreground")), .init(group: "Function", fg: hex("blue")),
            .init(group: "Statement", fg: hex("bright_magenta")), .init(group: "Operator", fg: hex("bright_blue")),
            .init(group: "PreProc", fg: hex("magenta")), .init(group: "Type", fg: hex("yellow")),
            .init(group: "Special", fg: hex("cyan")), .init(group: "SpecialChar", fg: hex("bright_cyan")),
            .init(group: "Tag", fg: hex("red")), .init(group: "Delimiter", fg: hex("foreground")),
            .init(group: "SpecialComment", fg: hex("muted"), styles: ["bold"]), .init(group: "Debug", fg: hex("red")),
            .init(group: "Underlined", fg: hex("accent"), styles: ["underline"]),
            .init(group: "Error", fg: hex("red")), .init(group: "Todo", fg: hex("yellow"), styles: ["bold"]),
        ] + links.map { Highlight(group: $0.0, link: $0.1) }
    }

    private static func treesitter(_ palette: ThemePalette) -> [Highlight] {
        let hex = { color(palette, $0) }
        let links = [
            ("@comment", "Comment"), ("@constant", "Constant"), ("@string", "String"), ("@number", "Number"),
            ("@boolean", "Boolean"), ("@type", "Type"), ("@function", "Function"), ("@function.method", "Function"),
            ("@keyword", "Keyword"), ("@operator", "Operator"), ("@markup.link", "Underlined"),
            ("@diff.plus", "Added"), ("@diff.minus", "Removed"), ("@diff.delta", "Changed"),
            ("@lsp.type.parameter", "@variable.parameter"), ("@lsp.type.property", "@property"),
            ("@lsp.type.namespace", "@module"), ("@lsp.type.enumMember", "@constant"),
            ("@lsp.type.decorator", "@attribute"), ("@lsp.type.macro", "@function.macro"),
        ]
        return [
            .init(group: "@variable", fg: hex("foreground")), .init(group: "@variable.parameter", fg: hex("cyan")),
            .init(group: "@variable.member", fg: hex("cyan")), .init(group: "@property", fg: hex("cyan")),
            .init(group: "@variable.builtin", fg: hex("red"), styles: ["italic"]),
            .init(group: "@constant.builtin", fg: hex("orange")), .init(group: "@module", fg: hex("blue")),
            .init(group: "@string.escape", fg: hex("bright_cyan")),
            .init(group: "@string.regexp", fg: hex("bright_cyan")),
            .init(group: "@type.builtin", fg: hex("yellow"), styles: ["italic"]),
            .init(group: "@function.builtin", fg: hex("cyan")), .init(group: "@function.macro", fg: hex("cyan")),
            .init(group: "@constructor", fg: hex("yellow")),
            .init(group: "@attribute", fg: hex("blue")),
            .init(group: "@punctuation.delimiter", fg: hex("foreground")),
            .init(group: "@punctuation.bracket", fg: hex("foreground")),
            .init(group: "@tag", fg: hex("red")), .init(group: "@tag.attribute", fg: hex("yellow"), styles: ["italic"]),
            .init(group: "@tag.delimiter", fg: hex("muted")),
            .init(group: "@markup.heading", fg: hex("accent"), styles: ["bold"]),
            .init(group: "@markup.strong", fg: hex("orange"), styles: ["bold"]),
            .init(group: "@markup.italic", fg: hex("magenta"), styles: ["italic"]),
            .init(group: "@markup.strikethrough", styles: ["strikethrough"]),
            .init(group: "@markup.raw", fg: hex("cyan")), .init(group: "@markup.list", fg: hex("bright_magenta")),
            .init(group: "@markup.link.url", fg: hex("blue"), styles: ["underline"]),
        ] + links.map { Highlight(group: $0.0, link: $0.1) }
    }

    private static func diagnostics(_ palette: ThemePalette) -> [Highlight] {
        let levels = [
            ("Error", palette.red), ("Warn", palette.yellow), ("Info", palette.blue),
            ("Hint", palette.cyan), ("Ok", palette.green),
        ]
        let perLevel = levels.flatMap { level, color in
            [
                Highlight(group: "Diagnostic\(level)", fg: color.hex),
                Highlight(group: "DiagnosticUnderline\(level)", sp: color.hex, styles: ["undercurl"]),
                Highlight(group: "DiagnosticVirtualText\(level)", fg: color.hex,
                          bg: palette.background.mix(color, 0.1).hex),
            ]
        }
        let raised = palette.lighterBackground.hex
        return perLevel + [
            .init(group: "DiagnosticUnnecessary", fg: palette.muted.hex),
            .init(group: "LspReferenceText", bg: raised), .init(group: "LspReferenceRead", bg: raised),
            .init(group: "LspReferenceWrite", bg: raised, styles: ["underline"]),
            .init(group: "LspInlayHint", fg: palette.muted.hex,
                  bg: palette.background.mix(palette.foreground, 0.05).hex),
            .init(group: "LspSignatureActiveParameter", fg: palette.accent.hex, styles: ["bold"]),
        ]
    }

    /// Popular plugins that don't fall back to the built-in groups on their own.
    private static let plugins: [Highlight] = [
        ("GitSignsAdd", "Added"), ("GitSignsChange", "Changed"), ("GitSignsDelete", "Removed"),
        ("TelescopeNormal", "NormalFloat"), ("TelescopeBorder", "FloatBorder"), ("TelescopeSelection", "PmenuSel"),
        ("TelescopeMatching", "PmenuMatch"), ("WhichKeyBorder", "FloatBorder"), ("NvimTreeNormal", "NormalFloat"),
        ("NeoTreeNormal", "NormalFloat"), ("NeoTreeNormalNC", "NormalFloat"),
    ].map { Highlight(group: $0.0, link: $0.1) }
}
