// Generated by scripts/generate-emoji.py — do not edit by hand.
// Sources: Unicode emoji-test.txt (fully-qualified, skin tones excluded)
// + CLDR en annotations for search keywords. 1914 entries.
// Excluded from SwiftLint via .swiftlint.yml.

enum EmojiData {
    /// One emoji per line: char \t name \t comma-separated keywords.
    static let tsv = """
    😀\tgrinning face\tcheerful,cheery,happy,laugh,nice,smile
    😃\tgrinning face with big eyes\tawesome,happy,mouth,open,smile,smiling
    😄\tgrinning face with smiling eyes\thappy,laugh,lol,mouth,open,smile
    😁\tbeaming face with smiling eyes\tgrin,grinning,happy,nice,smile,teeth
    😆\tgrinning squinting face\tclosed,eyes,haha,hahaha,happy,laugh
    😅\tgrinning face with sweat\tcold,dejected,excited,mouth,nervous,open
    🤣\trolling on the floor laughing\tcrying,face,funny,haha,happy,hehe
    😂\tface with tears of joy\tcrying,feels,funny,haha,happy,hehe
    🙂\tslightly smiling face\thappy,smile
    🙃\tupside-down face\thehe,smile
    🫠\tmelting face\tdisappear,dissolve,embarrassed,haha,heat,hot
    😉\twinking face\tflirt,heartbreaker,sexy,slide,tease,winks
    😊\tsmiling face with smiling eyes\tblush,glad,satisfied,smile
    😇\tsmiling face with halo\tangel,angelic,angels,blessed,fairy,fairytale
    🥰\tsmiling face with hearts\t3,adore,crush,ily,love,romance
    😍\tsmiling face with heart-eyes\t143,bae,feels,hearts,ily,kisses
    🤩\tstar-struck\texcited,eyes,face,grinning,smile,starry-eyed
    😘\tface blowing a kiss\tadorbs,bae,flirt,heart,ily,love
    😗\tkissing face\t143,date,dating,flirt,ily,love
    ☺️\tsmiling face\thappy,outlined,relaxed,smile
    😚\tkissing face with closed eyes\t143,bae,blush,date,dating,flirt
    😙\tkissing face with smiling eyes\t143,closed,date,dating,flirt,ily
    🥲\tsmiling face with tear\tglad,grateful,happy,joy,pain,proud
    😋\tface savoring food\tdelicious,eat,full,hungry,smile,smiling
    😛\tface with tongue\tawesome,cool,nice,party,stuck-out,sweet
    😜\twinking face with tongue\tcrazy,epic,eye,funny,joke,loopy
    🤪\tzany face\tcrazy,eye,eyes,goofy,large,small
    😝\tsquinting face with tongue\tclosed,eye,eyes,gross,horrible,omg
    🤑\tmoney-mouth face\tpaid
    🤗\tsmiling face with open hands\thug,hugging
    🤭\tface with hand over mouth\tgiggle,giggling,oops,realization,secret,shock
    🫢\tface with open eyes and hand over mouth\tamazement,awe,disbelief,embarrass,gasp,omg
    🫣\tface with peeking eye\tcaptivated,embarrass,hide,hiding,peep,scared
    🤫\tshushing face\tquiet,shh
    🤔\tthinking face\tchin,consider,hmm,ponder,pondering,wondering
    🫡\tsaluting face\tgood,luck,ma’am,ok,respect,salute
    🤐\tzipper-mouth face\tkeep,quiet,secret,shut
    🤨\tface with raised eyebrow\tdisapproval,disbelief,distrust,emoji,hmm,mild
    😐\tneutral face\tawkward,blank,deadpan,expressionless,fine,jealous
    😑\texpressionless face\tawkward,dead,fine,inexpressive,jealous,meh
    😶\tface without mouth\tawkward,blank,expressionless,mouthless,mute,quiet
    🫥\tdotted line face\tdepressed,disappear,hidden,hide,introvert,invisible
    😶‍🌫️\tface in clouds\tabsentminded,fog,head
    😏\tsmirking face\tboss,dapper,flirt,homie,kidding,leer
    😒\tunamused face\t...,bored,fine,jealous,jel,jelly
    🙄\tface with rolling eyes\teyeroll,shade,ugh,whatever
    😬\tgrimacing face\tawk,awkward,dentist,grimace,grinning,smile
    😮‍💨\tface exhaling\tblow,blowing,exhale,exhausted,gasp,groan
    🤥\tlying face\tliar,lie,pinocchio
    🫨\tshaking face\tcrazy,daze,earthquake,omg,panic,shock
    🙂‍↔️\thead shaking horizontally\tno,shake
    🙂‍↕️\thead shaking vertically\tnod,yes
    😌\trelieved face\tcalm,peace,relief,zen
    😔\tpensive face\tawful,bored,dejected,died,disappointed,losing
    😪\tsleepy face\tcrying,good,night,sad,sleeping,tired
    🤤\tdrooling face\t
    😴\tsleeping face\tbed,bedtime,good,goodnight,nap,night
    🫩\tface with bags under eyes\tbored,exhausted,fatigued,late,sleepy,tired
    😷\tface with medical mask\tcold,dentist,dermatologist,doctor,dr,germs
    🤒\tface with thermometer\till,sick
    🤕\tface with head-bandage\thurt,injury,ouch
    🤢\tnauseated face\tgross,nasty,sick,vomit
    🤮\tface vomiting\tbarf,ew,gross,puke,sick,spew
    🤧\tsneezing face\tfever,flu,gesundheit,sick,sneeze
    🥵\thot face\tdying,feverish,heat,panting,red-faced,stroke
    🥶\tcold face\tblue,blue-faced,freezing,frostbite,icicles,subzero
    🥴\twoozy face\tdizzy,drunk,eyes,intoxicated,mouth,tipsy
    😵\tface with crossed-out eyes\tdead,dizzy,feels,knocked,sick,tired
    😵‍💫\tface with spiral eyes\tconfused,dizzy,hypnotized,omg,smiley,trouble
    🤯\texploding head\tblown,explode,mind,mindblown,no,shocked
    🤠\tcowboy hat face\tcowgirl
    🥳\tpartying face\tbday,birthday,celebrate,celebration,excited,happy
    🥸\tdisguised face\teyebrow,glasses,incognito,moustache,mustache,nose
    😎\tsmiling face with sunglasses\tawesome,beach,bright,bro,chilling,cool
    🤓\tnerd face\tbrainy,clever,expert,geek,gifted,glasses
    🧐\tface with monocle\tclassy,fancy,rich,stuffy,wealthy
    😕\tconfused face\tbefuddled,confusing,dunno,frown,hm,meh
    🫤\tface with diagonal mouth\tconfused,confusion,disappointed,doubt,doubtful,frustrated
    😟\tworried face\tanxious,butterflies,nerves,nervous,sad,stress
    🙁\tslightly frowning face\tsad
    ☹️\tfrowning face\tsad
    😮\tface with open mouth\tbelieve,forgot,omg,shocked,surprised,sympathy
    😯\thushed face\tepic,omg,stunned,surprised,whoa,woah
    😲\tastonished face\tcost,no,omg,shocked,totally,way
    😳\tflushed face\tamazed,awkward,crazy,dazed,dead,disbelief
    🫪\tdistorted face\tanxiety,bloated,panic,shocked,surprised,vulnerable
    🥺\tpleading face\tbegging,big,eyes,mercy,not,please
    🥹\tface holding back tears\tadmiration,aww,cry,embarrassed,feelings,grateful
    😦\tfrowning face with open mouth\tcaught,guard,scared,scary,surprise,what
    😧\tanguished face\tforgot,scared,scary,stressed,surprise,unhappy
    😨\tfearful face\tafraid,anxious,blame,scared,worried
    😰\tanxious face with sweat\tblue,cold,eek,mouth,nervous,open
    😥\tsad but relieved face\tanxious,call,close,complicated,disappointed,not
    😢\tcrying face\tawful,feels,miss,sad,tear,triste
    😭\tloudly crying face\tbawling,sad,sob,tear,tears,unhappy
    😱\tface screaming in fear\tepic,fearful,munch,scared,screamer,shocked
    😖\tconfounded face\tannoyed,confused,cringe,distraught,feels,frustrated
    😣\tpersevering face\tconcentrate,concentration,focus,headache,persevere
    😞\tdisappointed face\tawful,blame,dejected,fail,losing,sad
    😓\tdowncast face with sweat\tclose,cold,feels,headache,nervous,sad
    😩\tweary face\tcrying,fail,feels,hungry,mad,nooo
    😫\ttired face\tcost,feels,nap,sad,sneeze
    🥱\tyawning face\tbedtime,bored,goodnight,nap,night,sleep
    😤\tface with steam from nose\tanger,angry,feels,fume,fuming,furious
    😡\tenraged face\tanger,angry,feels,mad,maddening,pouting
    😠\tangry face\tanger,blame,feels,frustrated,mad,maddening
    🤬\tface with symbols on mouth\tcensor,cursing,cussing,mad,pissed,swearing
    😈\tsmiling face with horns\tdemon,devil,evil,fairy,fairytale,fantasy
    👿\tangry face with horns\tdemon,devil,evil,fairy,fairytale,fantasy
    💀\tskull\tbody,dead,death,face,fairy,fairytale
    ☠️\tskull and crossbones\tdead,death,face,monster
    💩\tpile of poo\tbs,comic,doo,dung,face,fml
    🤡\tclown face\t
    👹\togre\tcreature,devil,face,fairy,fairytale,fantasy
    👺\tgoblin\tangry,creature,face,fairy,fairytale,fantasy
    👻\tghost\tboo,creature,excited,face,fairy,fairytale
    👽\talien\tcreature,extraterrestrial,face,fairy,fairytale,fantasy
    👾\talien monster\tcreature,extraterrestrial,face,fairy,fairytale,fantasy
    🤖\trobot\tface,monster
    😺\tgrinning cat\tanimal,face,mouth,open,smile,smiling
    😸\tgrinning cat with smiling eyes\tanimal,face,smile
    😹\tcat with tears of joy\tanimal,face,laugh,laughing,lol
    😻\tsmiling cat with heart-eyes\tanimal,face,love,smile
    😼\tcat with wry smile\tanimal,face,ironic
    😽\tkissing cat\tanimal,closed,eye,eyes,face
    🙀\tweary cat\tanimal,face,oh,surprised
    😿\tcrying cat\tanimal,face,sad,tear
    😾\tpouting cat\tanimal,face
    🙈\tsee-no-evil monkey\tembarrassed,face,forbidden,forgot,gesture,hide
    🙉\thear-no-evil monkey\tanimal,ears,face,forbidden,gesture,listen
    🙊\tspeak-no-evil monkey\tanimal,face,forbidden,gesture,not,oops
    💌\tlove letter\theart,mail,romance,valentine
    💘\theart with arrow\t143,adorbs,cupid,date,emotion,ily
    💝\theart with ribbon\t143,anniversary,emotion,ily,kisses,valentine
    💖\tsparkling heart\t143,emotion,excited,good,ily,kisses
    💗\tgrowing heart\t143,emotion,excited,heartpulse,ily,kisses
    💓\tbeating heart\t143,cardio,emotion,heartbeat,ily,love
    💞\trevolving hearts\t143,adorbs,anniversary,emotion
    💕\ttwo hearts\t143,anniversary,date,dating,emotion,ily
    💟\theart decoration\t143,emotion,hearth,purple,white
    ❣️\theart exclamation\theavy,mark,punctuation
    💔\tbroken heart\tbreak,crushed,emotion,heartbroken,lonely,sad
    ❤️‍🔥\theart on fire\tburn,love,lust,sacred
    ❤️‍🩹\tmending heart\thealthier,improving,recovering,recuperating,well
    ❤️\tred heart\temotion,love
    🩷\tpink heart\t143,adorable,cute,emotion,ily,like
    🧡\torange heart\t143
    💛\tyellow heart\t143,cardiac,emotion,ily,love
    💚\tgreen heart\t143,emotion,ily,love,romantic
    💙\tblue heart\t143,emotion,ily,love,romance
    🩵\tlight blue heart\t143,cute,cyan,emotion,ily,like
    💜\tpurple heart\t143,bestest,emotion,ily,love
    🤎\tbrown heart\t143
    🖤\tblack heart\tevil,wicked
    🩶\tgrey heart\t143,emotion,gray,ily,love,silver
    🤍\twhite heart\t143
    💋\tkiss mark\tdating,emotion,heart,kissing,lips,romance
    💯\thundred points\t100,a+,agree,clearly,definitely,faithful
    💢\tanger symbol\tangry,comic,mad,upset
    🫯\tfight cloud\targument,brawl,debate,disagreement,ruckus,wrestle
    💥\tcollision\tbomb,boom,collide,comic,explode
    💫\tdizzy\tcomic,shining,shooting,star,stars
    💦\tsweat droplets\tcomic,drip,drops,splashing,squirt,water
    💨\tdashing away\tcloud,comic,fart,fast,go,gone
    🕳️\thole\t
    💬\tspeech balloon\tbubble,comic,dialog,message,sms,talk
    👁️‍🗨️\teye in speech bubble\tballoon,witness
    🗨️\tleft speech bubble\tballoon,dialog
    🗯️\tright anger bubble\tangry,balloon,mad
    💭\tthought balloon\tbubble,cartoon,cloud,comic,daydream,decisions
    💤\tzzz\tcomic,good,goodnight,night,sleep,sleeping
    👋\twaving hand\tbye,cya,g2g,greetings,gtg,hello
    🤚\traised back of hand\tbackhand
    🖐️\thand with fingers splayed\traised,stop
    ✋\traised hand\t5,five,high,stop
    🖖\tvulcan salute\tfinger,hand,hands
    🫱\trightwards hand\thandshake,hold,reach,shake
    🫲\tleftwards hand\thandshake,hold,reach,shake
    🫳\tpalm down hand\tdismiss,drop,dropped,pick,shoo,up
    🫴\tpalm up hand\tbeckon,catch,come,hold,know,lift
    🫷\tleftwards pushing hand\tblock,five,halt,high,hold,pause
    🫸\trightwards pushing hand\tblock,five,halt,high,hold,pause
    👌\tok hand\tawesome,bet,dope,fleek,fosho,got
    🤌\tpinched fingers\tgesture,hand,hold,huh,interrogation,patience
    🤏\tpinching hand\tamount,bit,fingers,little,small,sort
    ✌️\tvictory hand\tpeace
    🤞\tcrossed fingers\thand,luck
    🫰\thand with index finger and thumb crossed\t<3,expensive,heart,love,money,snap
    🤟\tlove-you gesture\tfingers,hand,ily,three
    🤘\tsign of the horns\tfinger,hand,rock-on
    🤙\tcall me hand\thang,loose,shaka
    👈\tbackhand index pointing left\tfinger
    👉\tbackhand index pointing right\tfinger
    👆\tbackhand index pointing up\tfinger
    🖕\tmiddle finger\thand
    👇\tbackhand index pointing down\tfinger
    ☝️\tindex pointing up\tfinger,hand,this
    🫵\tindex pointing at the viewer\tfinger,hand,poke,you
    👍\tthumbs up\t+1,good,hand,like,yes
    👎\tthumbs down\t-1,bad,dislike,good,hand,no
    ✊\traised fist\tclenched,hand,punch,solidarity
    👊\toncoming fist\tabsolutely,agree,boom,bro,bruh,bump
    🤛\tleft-facing fist\tleftwards
    🤜\tright-facing fist\trightwards
    👏\tclapping hands\tapplause,approval,awesome,congrats,congratulations,excited
    🙌\traising hands\tcelebration,gesture,hooray,praise,raised
    🫶\theart hands\t<3,love,you
    👐\topen hands\thug,jazz,swerve
    🤲\tpalms up together\tcupped,dua,hands,pray,prayer,wish
    🤝\thandshake\tagreement,deal,meeting
    🙏\tfolded hands\tappreciate,ask,beg,blessed,bow,cmon
    ✍️\twriting hand\twrite
    💅\tnail polish\tbored,care,cosmetics,done,makeup,manicure
    🤳\tselfie\tcamera,phone
    💪\tflexed biceps\tarm,beast,bench,bodybuilder,bro,curls
    🦾\tmechanical arm\taccessibility,prosthetic
    🦿\tmechanical leg\taccessibility,prosthetic
    🦵\tleg\tbent,foot,kick,knee,limb
    🦶\tfoot\tankle,feet,kick,stomp
    👂\tear\tbody,ears,hear,hearing,listen,listening
    🦻\tear with hearing aid\taccessibility,hard
    👃\tnose\tbody,noses,nosey,odor,smell,smells
    🧠\tbrain\tintelligent,smart
    🫀\tanatomical heart\tbeat,cardiology,heartbeat,organ,pulse,real
    🫁\tlungs\tbreath,breathe,exhalation,inhalation,organ,respiration
    🦷\ttooth\tdentist,pearly,teeth,white
    🦴\tbone\tbones,dog,skeleton,wishbone
    👀\teyes\tbody,face,googly,look,looking,omg
    👁️\teye\t1,body,one
    👅\ttongue\tbody,lick,slurp
    👄\tmouth\tbeauty,body,kiss,kissing,lips,lipstick
    🫦\tbiting lip\tanxious,bite,fear,flirt,flirting,kiss
    👶\tbaby\tbabies,children,goo,infant,newborn,pregnant
    🧒\tchild\tbright-eyed,grandchild,kid,young,younger
    👦\tboy\tbright-eyed,child,grandson,kid,son,young
    👧\tgirl\tbright-eyed,child,daughter,granddaughter,kid,virgo
    🧑\tperson\tadult
    👱\tperson: blond hair\tblond-haired,human
    👨\tman\tadult,bro
    🧔\tperson: beard\tbearded,whiskers
    🧔‍♂️\tman: beard\tbearded,whiskers
    🧔‍♀️\twoman: beard\tbearded,whiskers
    👨‍🦰\tman: red hair\t
    👨‍🦱\tman: curly hair\t
    👨‍🦳\tman: white hair\t
    👨‍🦲\tman: bald\t
    👩\twoman\tadult,lady
    👩‍🦰\twoman: red hair\t
    🧑‍🦰\tperson: red hair\t
    👩‍🦱\twoman: curly hair\t
    🧑‍🦱\tperson: curly hair\t
    👩‍🦳\twoman: white hair\t
    🧑‍🦳\tperson: white hair\t
    👩‍🦲\twoman: bald\t
    🧑‍🦲\tperson: bald\t
    👱‍♀️\twoman: blond hair\tblond-haired,blonde
    👱‍♂️\tman: blond hair\tblond-haired
    🧓\tolder person\tadult,elderly,grandparent,wise
    👴\told man\tadult,bald,elderly,gramps,grandfather,grandpa
    👵\told woman\tadult,elderly,grandma,grandmother,granny,lady
    🙍\tperson frowning\tannoyed,disappointed,disgruntled,disturbed,frustrated,gesture
    🙍‍♂️\tman frowning\tannoyed,disappointed,disgruntled,disturbed,frustrated,gesture
    🙍‍♀️\twoman frowning\tannoyed,disappointed,disgruntled,disturbed,frustrated,gesture
    🙎\tperson pouting\tdisappointed,downtrodden,frown,grimace,scowl,sulk
    🙎‍♂️\tman pouting\tdisappointed,downtrodden,frown,grimace,scowl,sulk
    🙎‍♀️\twoman pouting\tdisappointed,downtrodden,frown,grimace,scowl,sulk
    🙅\tperson gesturing no\tforbidden,gesture,hand,not,prohibit
    🙅‍♂️\tman gesturing no\tforbidden,gesture,hand,not,prohibit
    🙅‍♀️\twoman gesturing no\tforbidden,gesture,hand,not,prohibit
    🙆\tperson gesturing ok\texercise,gesture,hand,omg
    🙆‍♂️\tman gesturing ok\texercise,gesture,hand,omg
    🙆‍♀️\twoman gesturing ok\texercise,gesture,hand,omg
    💁\tperson tipping hand\tfetch,flick,flip,gossip,sarcasm,sarcastic
    💁‍♂️\tman tipping hand\tfetch,flick,flip,gossip,sarcasm,sarcastic
    💁‍♀️\twoman tipping hand\tfetch,flick,flip,gossip,sarcasm,sarcastic
    🙋\tperson raising hand\tgesture,here,know,me,pick,question
    🙋‍♂️\tman raising hand\tgesture,here,know,me,pick,question
    🙋‍♀️\twoman raising hand\tgesture,here,know,me,pick,question
    🧏\tdeaf person\taccessibility,ear,gesture,hear
    🧏‍♂️\tdeaf man\taccessibility,ear,gesture,hear
    🧏‍♀️\tdeaf woman\taccessibility,ear,gesture,hear
    🙇\tperson bowing\tapology,ask,beg,favor,forgive,gesture
    🙇‍♂️\tman bowing\tapology,ask,beg,favor,forgive,gesture
    🙇‍♀️\twoman bowing\tapology,ask,beg,favor,forgive,gesture
    🤦\tperson facepalming\tagain,bewilder,disbelief,exasperation,no,not
    🤦‍♂️\tman facepalming\tagain,bewilder,disbelief,exasperation,no,not
    🤦‍♀️\twoman facepalming\tagain,bewilder,disbelief,exasperation,no,not
    🤷\tperson shrugging\tdoubt,dunno,guess,idk,ignorance,indifference
    🤷‍♂️\tman shrugging\tdoubt,dunno,guess,idk,ignorance,indifference
    🤷‍♀️\twoman shrugging\tdoubt,dunno,guess,idk,ignorance,indifference
    🧑‍⚕️\thealth worker\tdoctor,healthcare,nurse,therapist
    👨‍⚕️\tman health worker\tdoctor,healthcare,nurse,therapist
    👩‍⚕️\twoman health worker\tdoctor,healthcare,nurse,therapist
    🧑‍🎓\tstudent\tgraduate
    👨‍🎓\tman student\tgraduate
    👩‍🎓\twoman student\tgraduate
    🧑‍🏫\tteacher\tinstructor,lecturer,professor
    👨‍🏫\tman teacher\tinstructor,lecturer,professor
    👩‍🏫\twoman teacher\tinstructor,lecturer,professor
    🧑‍⚖️\tjudge\tjustice,law,scales
    👨‍⚖️\tman judge\tjustice,law,scales
    👩‍⚖️\twoman judge\tjustice,law,scales
    🧑‍🌾\tfarmer\tgardener,rancher
    👨‍🌾\tman farmer\tgardener,rancher
    👩‍🌾\twoman farmer\tgardener,rancher
    🧑‍🍳\tcook\tchef
    👨‍🍳\tman cook\tchef
    👩‍🍳\twoman cook\tchef
    🧑‍🔧\tmechanic\telectrician,plumber,tradesperson
    👨‍🔧\tman mechanic\telectrician,plumber,tradesperson
    👩‍🔧\twoman mechanic\telectrician,plumber,tradesperson
    🧑‍🏭\tfactory worker\tassembly,industrial
    👨‍🏭\tman factory worker\tassembly,industrial
    👩‍🏭\twoman factory worker\tassembly,industrial
    🧑‍💼\toffice worker\tarchitect,business,manager,white-collar
    👨‍💼\tman office worker\tarchitect,business,manager,white-collar
    👩‍💼\twoman office worker\tarchitect,business,manager,white-collar
    🧑‍🔬\tscientist\tbiologist,chemist,engineer,mathematician,physicist
    👨‍🔬\tman scientist\tbiologist,chemist,engineer,mathematician,physicist
    👩‍🔬\twoman scientist\tbiologist,chemist,engineer,mathematician,physicist
    🧑‍💻\ttechnologist\tcoder,computer,developer,inventor,software
    👨‍💻\tman technologist\tcoder,computer,developer,inventor,software
    👩‍💻\twoman technologist\tcoder,computer,developer,inventor,software
    🧑‍🎤\tsinger\tactor,entertainer,rock,rockstar,star
    👨‍🎤\tman singer\tactor,entertainer,rock,rockstar,star
    👩‍🎤\twoman singer\tactor,entertainer,rock,rockstar,star
    🧑‍🎨\tartist\tpalette
    👨‍🎨\tman artist\tpalette
    👩‍🎨\twoman artist\tpalette
    🧑‍✈️\tpilot\tplane
    👨‍✈️\tman pilot\tplane
    👩‍✈️\twoman pilot\tplane
    🧑‍🚀\tastronaut\trocket,space
    👨‍🚀\tman astronaut\trocket,space
    👩‍🚀\twoman astronaut\trocket,space
    🧑‍🚒\tfirefighter\tfiretruck
    👨‍🚒\tman firefighter\tfiretruck
    👩‍🚒\twoman firefighter\tfiretruck
    👮\tpolice officer\tapprehend,arrest,citation,cop,law,over
    👮‍♂️\tman police officer\tapprehend,arrest,citation,cop,law,over
    👮‍♀️\twoman police officer\tapprehend,arrest,citation,cop,law,over
    🕵️\tdetective\tsleuth,spy
    🕵️‍♂️\tman detective\tsleuth,spy
    🕵️‍♀️\twoman detective\tsleuth,spy
    💂\tguard\tbuckingham,helmet,london,palace
    💂‍♂️\tman guard\tbuckingham,helmet,london,palace
    💂‍♀️\twoman guard\tbuckingham,helmet,london,palace
    🥷\tninja\tassassin,fight,fighter,hidden,person,secret
    👷\tconstruction worker\tbuild,fix,hardhat,hat,man,person
    👷‍♂️\tman construction worker\tbuild,fix,hardhat,hat,rebuild,remodel
    👷‍♀️\twoman construction worker\tbuild,fix,hardhat,hat,rebuild,remodel
    🫅\tperson with crown\tmonarch,noble,regal,royal,royalty
    🤴\tprince\tcrown,fairy,fairytale,fantasy,king,royal
    👸\tprincess\tcrown,fairy,fairytale,fantasy,queen,royal
    👳\tperson wearing turban\t
    👳‍♂️\tman wearing turban\t
    👳‍♀️\twoman wearing turban\t
    👲\tperson with skullcap\tchinese,gua,guapi,hat,mao,pi
    🧕\twoman with headscarf\tbandana,hijab,kerchief,mantilla,tichel
    🤵\tperson in tuxedo\tformal,wedding
    🤵‍♂️\tman in tuxedo\tformal,groom,wedding
    🤵‍♀️\twoman in tuxedo\tformal,wedding
    👰\tperson with veil\twedding
    👰‍♂️\tman with veil\twedding
    👰‍♀️\twoman with veil\tbride,wedding
    🤰\tpregnant woman\t
    🫃\tpregnant man\tbelly,bloated,full,overeat
    🫄\tpregnant person\tbelly,bloated,full,overeat,stuffed
    🤱\tbreast-feeding\tbaby,mom,mother,nursing,woman
    👩‍🍼\twoman feeding baby\tmom,mother,nanny,newborn,nursing
    👨‍🍼\tman feeding baby\tdad,father,nanny,newborn,nursing
    🧑‍🍼\tperson feeding baby\tnanny,newborn,nursing,parent
    👼\tbaby angel\tchurch,face,fairy,fairytale,fantasy,tale
    🎅\tsanta claus\tcelebration,christmas,fairy,fantasy,father,holiday
    🤶\tmrs. claus\tcelebration,christmas,fairy,fantasy,holiday,merry
    🧑‍🎄\tmx claus\tcelebration,christmas,fairy,fantasy,holiday,merry
    🦸\tsuperhero\tgood,superpower
    🦸‍♂️\tman superhero\tgood,superpower
    🦸‍♀️\twoman superhero\tgood,heroine,superpower
    🦹\tsupervillain\tbad,criminal,evil,superpower
    🦹‍♂️\tman supervillain\tbad,criminal,evil,superpower
    🦹‍♀️\twoman supervillain\tbad,criminal,evil,superpower
    🧙\tmage\tfantasy,magic,play,sorcerer,sorceress,sorcery
    🧙‍♂️\tman mage\tfantasy,magic,play,sorcerer,sorceress,sorcery
    🧙‍♀️\twoman mage\tfantasy,magic,play,sorcerer,sorceress,sorcery
    🧚\tfairy\tfairytale,fantasy,myth,person,pixie,tale
    🧚‍♂️\tman fairy\tfairytale,fantasy,myth,oberon,person,pixie
    🧚‍♀️\twoman fairy\tfairytale,fantasy,myth,person,pixie,tale
    🧛\tvampire\tblood,dracula,fangs,halloween,scary,supernatural
    🧛‍♂️\tman vampire\tblood,fangs,halloween,scary,supernatural,teeth
    🧛‍♀️\twoman vampire\tblood,fangs,halloween,scary,supernatural,teeth
    🧜\tmerperson\tcreature,fairytale,folklore,ocean,sea,siren
    🧜‍♂️\tmerman\tcreature,fairytale,folklore,neptune,ocean,poseidon
    🧜‍♀️\tmermaid\tcreature,fairytale,folklore,merwoman,ocean,sea
    🧝\telf\telves,enchantment,fantasy,folklore,magic,magical
    🧝‍♂️\tman elf\telves,enchantment,fantasy,folklore,magic,magical
    🧝‍♀️\twoman elf\telves,enchantment,fantasy,folklore,magic,magical
    🧞\tgenie\tdjinn,fantasy,jinn,lamp,myth,rub
    🧞‍♂️\tman genie\tdjinn,fantasy,jinn,lamp,myth,rub
    🧞‍♀️\twoman genie\tdjinn,fantasy,jinn,lamp,myth,rub
    🧟\tzombie\tapocalypse,dead,halloween,horror,scary,undead
    🧟‍♂️\tman zombie\tapocalypse,dead,halloween,horror,scary,undead
    🧟‍♀️\twoman zombie\tapocalypse,dead,halloween,horror,scary,undead
    🧌\ttroll\tfairy,fantasy,monster,tale,trolling
    🫈\thairy creature\tbigfoot,cryptid,forest,giant,sasquatch,woodwose
    💆\tperson getting massage\tface,headache,relax,relaxing,salon,soothe
    💆‍♂️\tman getting massage\tface,headache,relax,relaxing,salon,soothe
    💆‍♀️\twoman getting massage\tface,headache,relax,relaxing,salon,soothe
    💇\tperson getting haircut\tbarber,beauty,chop,cosmetology,groom,parlor
    💇‍♂️\tman getting haircut\tbarber,beauty,chop,cosmetology,groom,parlor
    💇‍♀️\twoman getting haircut\tbarber,beauty,chop,cosmetology,groom,parlor
    🚶\tperson walking\tamble,gait,hike,man,pace,pedestrian
    🚶‍♂️\tman walking\tamble,gait,hike,pace,pedestrian,stride
    🚶‍♀️\twoman walking\tamble,gait,hike,pace,pedestrian,stride
    🚶‍➡️\tperson walking facing right\t
    🚶‍♀️‍➡️\twoman walking facing right\t
    🚶‍♂️‍➡️\tman walking facing right\t
    🧍\tperson standing\t
    🧍‍♂️\tman standing\t
    🧍‍♀️\twoman standing\t
    🧎\tperson kneeling\tknees
    🧎‍♂️\tman kneeling\tknees
    🧎‍♀️\twoman kneeling\tknees
    🧎‍➡️\tperson kneeling facing right\t
    🧎‍♀️‍➡️\twoman kneeling facing right\t
    🧎‍♂️‍➡️\tman kneeling facing right\t
    🧑‍🦯\tperson with white cane\taccessibility,blind,probing
    🧑‍🦯‍➡️\tperson with white cane facing right\t
    👨‍🦯\tman with white cane\taccessibility,blind,probing
    👨‍🦯‍➡️\tman with white cane facing right\t
    👩‍🦯\twoman with white cane\taccessibility,blind,probing
    👩‍🦯‍➡️\twoman with white cane facing right\t
    🧑‍🦼\tperson in motorized wheelchair\taccessibility
    🧑‍🦼‍➡️\tperson in motorized wheelchair facing right\t
    👨‍🦼\tman in motorized wheelchair\taccessibility
    👨‍🦼‍➡️\tman in motorized wheelchair facing right\t
    👩‍🦼\twoman in motorized wheelchair\taccessibility
    👩‍🦼‍➡️\twoman in motorized wheelchair facing right\t
    🧑‍🦽\tperson in manual wheelchair\taccessibility
    🧑‍🦽‍➡️\tperson in manual wheelchair facing right\t
    👨‍🦽\tman in manual wheelchair\taccessibility
    👨‍🦽‍➡️\tman in manual wheelchair facing right\t
    👩‍🦽\twoman in manual wheelchair\taccessibility
    👩‍🦽‍➡️\twoman in manual wheelchair facing right\t
    🏃\tperson running\tfast,hurry,marathon,move,quick,race
    🏃‍♂️\tman running\tfast,hurry,marathon,move,quick,race
    🏃‍♀️\twoman running\tfast,hurry,marathon,move,quick,race
    🏃‍➡️\tperson running facing right\t
    🏃‍♀️‍➡️\twoman running facing right\t
    🏃‍♂️‍➡️\tman running facing right\t
    🧑‍🩰\tballet dancer\t
    💃\twoman dancing\tdance,dancer,elegant,festive,flair,flamenco
    🕺\tman dancing\tdance,dancer,elegant,festive,flair,flamenco
    🕴️\tperson in suit levitating\tbusiness
    👯\tpeople with bunny ears\tbestie,bff,counterpart,dancer,double,identical
    👯‍♂️\tmen with bunny ears\tbestie,bff,counterpart,dancer,double,identical
    👯‍♀️\twomen with bunny ears\tbestie,bff,counterpart,dancer,double,identical
    🧖\tperson in steamy room\tday,luxurious,pamper,relax,sauna,spa
    🧖‍♂️\tman in steamy room\tday,luxurious,pamper,relax,sauna,spa
    🧖‍♀️\twoman in steamy room\tday,luxurious,pamper,relax,sauna,spa
    🧗\tperson climbing\tclimber,mountain,rock,scale,up
    🧗‍♂️\tman climbing\tclimber,mountain,rock,scale,up
    🧗‍♀️\twoman climbing\tclimber,mountain,rock,scale,up
    🤺\tperson fencing\tfencer,sword
    🏇\thorse racing\tjockey,racehorse,riding,sport
    ⛷️\tskier\tsnow
    🏂\tsnowboarder\tski,sport
    🏌️\tperson golfing\tball,birdie,caddy,driving,green,pga
    🏌️‍♂️\tman golfing\tball,birdie,caddy,driving,green,pga
    🏌️‍♀️\twoman golfing\tball,birdie,caddy,driving,green,pga
    🏄\tperson surfing\tbeach,ocean,sport,surfer,swell,waves
    🏄‍♂️\tman surfing\tbeach,ocean,sport,surfer,swell,waves
    🏄‍♀️\twoman surfing\tbeach,ocean,person,sport,surfer,swell
    🚣\tperson rowing boat\tcanoe,cruise,fishing,lake,oar,paddle
    🚣‍♂️\tman rowing boat\tcanoe,cruise,fishing,lake,oar,paddle
    🚣‍♀️\twoman rowing boat\tcanoe,cruise,fishing,lake,oar,paddle
    🏊\tperson swimming\tfreestyle,sport,swimmer,triathlon
    🏊‍♂️\tman swimming\tfreestyle,sport,swimmer,triathlon
    🏊‍♀️\twoman swimming\tfreestyle,sport,swimmer,triathlon
    ⛹️\tperson bouncing ball\tathletic,basketball,championship,dribble,net,player
    ⛹️‍♂️\tman bouncing ball\tathletic,basketball,championship,dribble,net,player
    ⛹️‍♀️\twoman bouncing ball\tathletic,basketball,championship,dribble,net,player
    🏋️\tperson lifting weights\tbarbell,bodybuilder,deadlift,lifter,powerlifting,weightlifter
    🏋️‍♂️\tman lifting weights\tbarbell,bodybuilder,deadlift,lifter,powerlifting,weightlifter
    🏋️‍♀️\twoman lifting weights\tbarbell,bodybuilder,deadlift,lifter,powerlifting,weightlifter
    🚴\tperson biking\tbicycle,bicyclist,bike,cycle,cyclist,riding
    🚴‍♂️\tman biking\tbicycle,bicyclist,bike,cycle,cyclist,riding
    🚴‍♀️\twoman biking\tbicycle,bicyclist,bike,cycle,cyclist,riding
    🚵\tperson mountain biking\tbicycle,bicyclist,bike,cycle,cyclist,riding
    🚵‍♂️\tman mountain biking\tbicycle,bicyclist,bike,cycle,cyclist,riding
    🚵‍♀️\twoman mountain biking\tbicycle,bicyclist,bike,cycle,cyclist,riding
    🤸\tperson cartwheeling\tactive,excited,flip,gymnastics,happy,somersault
    🤸‍♂️\tman cartwheeling\tactive,excited,flip,gymnastics,happy,somersault
    🤸‍♀️\twoman cartwheeling\tactive,excited,flip,gymnastics,happy,somersault
    🤼\tpeople wrestling\tcombat,duel,grapple,ring,tournament,wrestle
    🤼‍♂️\tmen wrestling\tcombat,duel,grapple,ring,tournament,wrestle
    🤼‍♀️\twomen wrestling\tcombat,duel,grapple,ring,tournament,wrestle
    🤽\tperson playing water polo\tsport,swimming,waterpolo
    🤽‍♂️\tman playing water polo\tsport,swimming,waterpolo
    🤽‍♀️\twoman playing water polo\tsport,swimming,waterpolo
    🤾\tperson playing handball\tathletics,catch,chuck,hurl,lob,pitch
    🤾‍♂️\tman playing handball\tathletics,catch,chuck,hurl,lob,pitch
    🤾‍♀️\twoman playing handball\tathletics,catch,chuck,hurl,lob,pitch
    🤹\tperson juggling\tact,balance,balancing,handle,juggle,manage
    🤹‍♂️\tman juggling\tact,balance,balancing,handle,juggle,manage
    🤹‍♀️\twoman juggling\tact,balance,balancing,handle,juggle,manage
    🧘\tperson in lotus position\tcross,legged,legs,meditation,peace,relax
    🧘‍♂️\tman in lotus position\tcross,legged,legs,meditation,peace,relax
    🧘‍♀️\twoman in lotus position\tcross,legged,legs,meditation,peace,relax
    🛀\tperson taking bath\tbathtub,tub
    🛌\tperson in bed\tbedtime,good,goodnight,hotel,nap,night
    🧑‍🤝‍🧑\tpeople holding hands\tbae,bestie,bff,couple,dating,flirt
    👭\twomen holding hands\tbae,bestie,bff,couple,dating,flirt
    👫\twoman and man holding hands\tbae,bestie,bff,couple,dating,flirt
    👬\tmen holding hands\tbae,bestie,bff,boys,brothers,couple
    💏\tkiss\tanniversary,babe,bae,couple,date,dating
    👩‍❤️‍💋‍👨\tkiss: woman, man\t
    👨‍❤️‍💋‍👨\tkiss: man, man\t
    👩‍❤️‍💋‍👩\tkiss: woman, woman\t
    💑\tcouple with heart\tanniversary,babe,bae,dating,kiss,love
    👩‍❤️‍👨\tcouple with heart: woman, man\t
    👨‍❤️‍👨\tcouple with heart: man, man\t
    👩‍❤️‍👩\tcouple with heart: woman, woman\t
    👨‍👩‍👦\tfamily: man, woman, boy\t
    👨‍👩‍👧\tfamily: man, woman, girl\t
    👨‍👩‍👧‍👦\tfamily: man, woman, girl, boy\t
    👨‍👩‍👦‍👦\tfamily: man, woman, boy, boy\t
    👨‍👩‍👧‍👧\tfamily: man, woman, girl, girl\t
    👨‍👨‍👦\tfamily: man, man, boy\t
    👨‍👨‍👧\tfamily: man, man, girl\t
    👨‍👨‍👧‍👦\tfamily: man, man, girl, boy\t
    👨‍👨‍👦‍👦\tfamily: man, man, boy, boy\t
    👨‍👨‍👧‍👧\tfamily: man, man, girl, girl\t
    👩‍👩‍👦\tfamily: woman, woman, boy\t
    👩‍👩‍👧\tfamily: woman, woman, girl\t
    👩‍👩‍👧‍👦\tfamily: woman, woman, girl, boy\t
    👩‍👩‍👦‍👦\tfamily: woman, woman, boy, boy\t
    👩‍👩‍👧‍👧\tfamily: woman, woman, girl, girl\t
    👨‍👦\tfamily: man, boy\t
    👨‍👦‍👦\tfamily: man, boy, boy\t
    👨‍👧\tfamily: man, girl\t
    👨‍👧‍👦\tfamily: man, girl, boy\t
    👨‍👧‍👧\tfamily: man, girl, girl\t
    👩‍👦\tfamily: woman, boy\t
    👩‍👦‍👦\tfamily: woman, boy, boy\t
    👩‍👧\tfamily: woman, girl\t
    👩‍👧‍👦\tfamily: woman, girl, boy\t
    👩‍👧‍👧\tfamily: woman, girl, girl\t
    🗣️\tspeaking head\tface,silhouette
    👤\tbust in silhouette\tmysterious,shadow
    👥\tbusts in silhouette\tbff,everyone,friend,friends,people
    🫂\tpeople hugging\tcomfort,embrace,farewell,friendship,goodbye,hello
    👪\tfamily\tchild
    🧑‍🧑‍🧒\tfamily: adult, adult, child\t
    🧑‍🧑‍🧒‍🧒\tfamily: adult, adult, child, child\t
    🧑‍🧒\tfamily: adult, child\t
    🧑‍🧒‍🧒\tfamily: adult, child, child\t
    👣\tfootprints\tbarefoot,clothing,omw,walk
    🫆\tfingerprint\tclue,crime,detective,forensics,identity,mystery
    🐵\tmonkey face\tanimal,banana
    🐒\tmonkey\tanimal,banana
    🦍\tgorilla\tanimal
    🦧\torangutan\tanimal,ape,monkey
    🐶\tdog face\tadorbs,animal,pet,puppies,puppy
    🐕\tdog\tanimal,animals,dogs,pet
    🦮\tguide dog\taccessibility,animal,blind
    🐕‍🦺\tservice dog\taccessibility,animal,assistance
    🐩\tpoodle\tanimal,dog,fluffy
    🐺\twolf\tanimal,face
    🦊\tfox\tanimal,face
    🦝\traccoon\tanimal,curious,sly
    🐱\tcat face\tanimal,kitten,kitty,pet
    🐈\tcat\tanimal,animals,cats,kitten,pet
    🐈‍⬛\tblack cat\tanimal,feline,halloween,meow,unlucky
    🦁\tlion\talpha,animal,face,leo,mane,order
    🐯\ttiger face\tanimal,big,cat,predator
    🐅\ttiger\tanimal,big,cat,predator,zoo
    🐆\tleopard\tanimal,big,cat,predator,zoo
    🐴\thorse face\tanimal,dressage,equine,farm,horses
    🫎\tmoose\talces,animal,antlers,elk,mammal
    🫏\tdonkey\tanimal,ass,burro,hinny,mammal,mule
    🐎\thorse\tanimal,equestrian,farm,racehorse,racing
    🦄\tunicorn\tface
    🦓\tzebra\tanimal,stripe
    🦌\tdeer\tanimal
    🦬\tbison\tanimal,buffalo,herd,wisent
    🐮\tcow face\tanimal,farm,milk,moo
    🐂\tox\tanimal,animals,bull,farm,taurus,zodiac
    🐃\twater buffalo\tanimal,zoo
    🐄\tcow\tanimal,animals,farm,milk,moo
    🐷\tpig face\tanimal,bacon,farm,pork
    🐖\tpig\tanimal,bacon,farm,pork,sow
    🐗\tboar\tanimal,pig
    🐽\tpig nose\tanimal,face,farm,smell,snout
    🐏\tram\tanimal,aries,horns,male,sheep,zodiac
    🐑\tewe\tanimal,baa,farm,female,fluffy,lamb
    🐐\tgoat\tanimal,capricorn,farm,milk,zodiac
    🐪\tcamel\tanimal,desert,dromedary,hump,one
    🐫\ttwo-hump camel\tanimal,bactrian,desert
    🦙\tllama\talpaca,animal,guanaco,vicuña,wool
    🦒\tgiraffe\tanimal,spots
    🐘\telephant\tanimal
    🦣\tmammoth\tanimal,extinction,large,tusk,wooly
    🦏\trhinoceros\tanimal
    🦛\thippopotamus\tanimal
    🐭\tmouse face\tanimal
    🐁\tmouse\tanimal,animals
    🐀\trat\tanimal
    🐹\thamster\tanimal,face,pet
    🐰\trabbit face\tanimal,bunny,pet
    🐇\trabbit\tanimal,bunny,pet
    🐿️\tchipmunk\tanimal,squirrel
    🦫\tbeaver\tanimal,dam,teeth
    🦔\thedgehog\tanimal,spiny
    🦇\tbat\tanimal,vampire
    🐻\tbear\tanimal,face,grizzly,growl,honey
    🐻‍❄️\tpolar bear\tanimal,arctic,white
    🐨\tkoala\tanimal,australia,bear,down,face,marsupial
    🐼\tpanda\tanimal,bamboo,face
    🦥\tsloth\tlazy,slow
    🦦\totter\tanimal,fishing,playful
    🦨\tskunk\tanimal,stink
    🦘\tkangaroo\tanimal,joey,jump,marsupial
    🦡\tbadger\tanimal,honey,pester
    🐾\tpaw prints\tfeet,paws
    🦃\tturkey\tbird,gobble,thanksgiving
    🐔\tchicken\tanimal,bird,ornithology
    🐓\trooster\tanimal,bird,ornithology
    🐣\thatching chick\tanimal,baby,bird,egg
    🐤\tbaby chick\tanimal,bird,ornithology
    🐥\tfront-facing baby chick\tanimal,bird,newborn,ornithology
    🐦\tbird\tanimal,ornithology
    🐧\tpenguin\tanimal,antarctica,bird,ornithology
    🕊️\tdove\tbird,fly,ornithology,peace
    🦅\teagle\tanimal,bird,ornithology
    🦆\tduck\tanimal,bird,ornithology
    🦢\tswan\tanimal,bird,cygnet,duckling,ornithology,ugly
    🦉\towl\tanimal,bird,ornithology,wise
    🦤\tdodo\tanimal,bird,extinction,large,ornithology
    🪶\tfeather\tbird,flight,light,plumage
    🦩\tflamingo\tanimal,bird,flamboyant,ornithology,tropical
    🦚\tpeacock\tanimal,bird,colorful,ornithology,ostentatious,peahen
    🦜\tparrot\tanimal,bird,ornithology,pirate,talk
    🪽\twing\tangelic,ascend,aviation,bird,fly,flying
    🐦‍⬛\tblack bird\tanimal,beak,caw,corvid,crow,ornithology
    🪿\tgoose\tanimal,bird,duck,flock,fowl,gaggle
    🐦‍🔥\tphoenix\tascend,ascension,emerge,fantasy,firebird,glory
    🐸\tfrog\tanimal,face
    🐊\tcrocodile\tanimal,zoo
    🐢\tturtle\tanimal,terrapin,tortoise
    🦎\tlizard\tanimal,reptile
    🐍\tsnake\tanimal,bearer,ophiuchus,serpent,zodiac
    🐲\tdragon face\tanimal,fairy,fairytale,tale
    🐉\tdragon\tanimal,fairy,fairytale,knights,tale
    🦕\tsauropod\tbrachiosaurus,brontosaurus,dinosaur,diplodocus
    🦖\tt-rex\tdinosaur,tyrannosaurus
    🐳\tspouting whale\tanimal,beach,face,ocean
    🐋\twhale\tanimal,beach,ocean
    🐬\tdolphin\tanimal,beach,flipper,ocean
    🫍\torca\tmarine,ocean,whale
    🦭\tseal\tanimal,lion,ocean
    🐟\tfish\tanimal,dinner,fishes,fishing,pisces,zodiac
    🐠\ttropical fish\tanimal,fishes
    🐡\tblowfish\tanimal
    🦈\tshark\tanimal,fish
    🐙\toctopus\tanimal,creature,ocean
    🐚\tspiral shell\tanimal,beach,conch,sea
    🪸\tcoral\tchange,climate,ocean,reef,sea
    🪼\tjellyfish\tanimal,aquarium,burn,invertebrate,life,marine
    🦀\tcrab\tcancer,zodiac
    🦞\tlobster\tanimal,bisque,claws,seafood
    🦐\tshrimp\tfood,shellfish,small
    🦑\tsquid\tanimal,food,mollusk
    🦪\toyster\tdiving,pearl
    🐌\tsnail\tanimal,escargot,garden,nature,slug
    🦋\tbutterfly\tinsect,pretty
    🐛\tbug\tanimal,garden,insect
    🐜\tant\tanimal,garden,insect
    🐝\thoneybee\tanimal,bumblebee,insect,nature,spring
    🪲\tbeetle\tanimal,bug,insect
    🐞\tlady beetle\tanimal,garden,insect,ladybird,ladybug,nature
    🦗\tcricket\tanimal,bug,grasshopper,insect,orthoptera
    🪳\tcockroach\tanimal,insect,pest
    🕷️\tspider\tanimal,insect
    🕸️\tspider web\t
    🦂\tscorpion\tscorpius,zodiac
    🦟\tmosquito\tbite,disease,fever,insect,malaria,pest
    🪰\tfly\tanimal,disease,insect,maggot,pest,rotting
    🪱\tworm\tanimal,annelid,earthworm,parasite
    🦠\tmicrobe\tamoeba,bacteria,science,virus
    💐\tbouquet\tanniversary,birthday,date,flower,love,plant
    🌸\tcherry blossom\tflower,plant,spring,springtime
    💮\twhite flower\t
    🪷\tlotus\tbeauty,buddhism,calm,flower,hinduism,peace
    🏵️\trosette\tplant
    🌹\trose\tbeauty,elegant,flower,love,plant,red
    🥀\twilted flower\tdying
    🌺\thibiscus\tflower,plant
    🌻\tsunflower\toutdoors,plant
    🌼\tblossom\tbuttercup,dandelion,flower,plant
    🌷\ttulip\tblossom,flower,growth,plant
    🪻\thyacinth\tbloom,bluebonnet,flower,indigo,lavender,lilac
    🌱\tseedling\tplant,sapling,sprout,young
    🪴\tpotted plant\tdecor,grow,house,nurturing
    🌲\tevergreen tree\tchristmas,forest,pine
    🌳\tdeciduous tree\tforest,green,habitat,shedding
    🌴\tpalm tree\tbeach,plant,tropical
    🌵\tcactus\tdesert,drought,nature,plant
    🌾\tsheaf of rice\tear,grain,grains,plant
    🌿\therb\tleaf,plant
    ☘️\tshamrock\tirish,plant
    🍀\tfour leaf clover\t4,four-leaf,irish,lucky,plant
    🍁\tmaple leaf\tfalling
    🍂\tfallen leaf\tautumn,falling
    🍃\tleaf fluttering in wind\tblow
    🪹\tempty nest\tbranch,home,nesting
    🪺\tnest with eggs\tbird,branch,nesting
    🍄\tmushroom\tfungus,toadstool
    🪾\tleafless tree\tbare,barren,branches,dead,drought,trunk
    🍇\tgrapes\tdionysus,fruit
    🍈\tmelon\tcantaloupe,fruit
    🍉\twatermelon\tfruit
    🍊\ttangerine\tc,citrus,fruit,nectarine,orange,vitamin
    🍋\tlemon\tcitrus,fruit,sour
    🍋‍🟩\tlime\tacidity,citrus,cocktail,fruit,garnish,key
    🍌\tbanana\tfruit,potassium
    🍍\tpineapple\tcolada,fruit,pina,tropical
    🥭\tmango\tfood,fruit,tropical
    🍎\tred apple\tdiet,food,fruit,health,ripe
    🍏\tgreen apple\tfruit
    🍐\tpear\tfruit
    🍑\tpeach\tfruit
    🍒\tcherries\tberries,cherry,fruit,red
    🍓\tstrawberry\tfruit
    🫐\tblueberries\tberry,bilberry,blueberry,food,fruit
    🥝\tkiwi fruit\tfood
    🍅\ttomato\tfood,fruit,vegetable
    🫒\tolive\tfood
    🥥\tcoconut\tcolada,palm,piña
    🥑\tavocado\tfood,fruit
    🍆\teggplant\taubergine,vegetable
    🥔\tpotato\tfood,vegetable
    🥕\tcarrot\tfood,vegetable
    🌽\tear of corn\tcrops,farm,maize,maze
    🌶️\thot pepper\t
    🫑\tbell pepper\tcapsicum,food,vegetable
    🥒\tcucumber\tfood,pickle,vegetable
    🥬\tleafy green\tbok,burgers,cabbage,choy,kale,lettuce
    🥦\tbroccoli\tcabbage,wild
    🧄\tgarlic\tflavoring
    🧅\tonion\tflavoring
    🥜\tpeanuts\tfood,vegetable
    🫘\tbeans\tfood,kidney,legume,small
    🌰\tchestnut\talmond,plant
    🫚\tginger root\tbeer,health,herb,natural,spice
    🫛\tpea pod\tbeans,beanstalk,edamame,legume,soybean,vegetable
    🍄‍🟫\tbrown mushroom\tfood,fungi,fungus,nature,pizza,portobello
    🫜\troot vegetable\tbeet,food,garden,radish,salad,turnip
    🍞\tbread\tcarbs,food,grain,loaf,restaurant,toast
    🥐\tcroissant\tbread,breakfast,crescent,food,french,roll
    🥖\tbaguette bread\tfood,french
    🫓\tflatbread\tarepa,food,gordita,lavash,naan,pita
    🥨\tpretzel\tconvoluted,twisted
    🥯\tbagel\tbakery,bread,breakfast,schmear
    🥞\tpancakes\tbreakfast,crêpe,food,hotcake
    🧇\twaffle\tbreakfast,indecisive,iron
    🧀\tcheese wedge\t
    🍖\tmeat on bone\t
    🍗\tpoultry leg\tbone,chicken,drumstick,hungry,turkey
    🥩\tcut of meat\tchop,lambchop,porkchop,red,steak
    🥓\tbacon\tbreakfast,food,meat
    🍔\thamburger\teat,fast,food,hungry
    🍟\tfrench fries\tfast,food
    🍕\tpizza\tcheese,food,hungry,pepperoni,slice
    🌭\thot dog\tfrankfurter,hotdog,sausage
    🥪\tsandwich\tbread
    🌮\ttaco\tmexican
    🌯\tburrito\tmexican,wrap
    🫔\ttamale\tfood,mexican,pamonha,wrapped
    🥙\tstuffed flatbread\tfalafel,food,gyro,kebab
    🧆\tfalafel\tchickpea,meatball
    🥚\tegg\tbreakfast,food
    🍳\tcooking\tbreakfast,easy,egg,fry,frying,over
    🥘\tshallow pan of food\tcasserole,paella
    🍲\tpot of food\tsoup,stew
    🫕\tfondue\tcheese,chocolate,food,melted,pot,ski
    🥣\tbowl with spoon\tbreakfast,cereal,congee,oatmeal,porridge
    🥗\tgreen salad\tfood
    🍿\tpopcorn\tmovie
    🧈\tbutter\tdairy
    🧂\tsalt\tcondiment,flavor,mad,salty,shaker,taste
    🥫\tcanned food\t
    🍱\tbento box\tfood
    🍘\trice cracker\tfood
    🍙\trice ball\tfood,japanese
    🍚\tcooked rice\tfood
    🍛\tcurry rice\tfood
    🍜\tsteaming bowl\tchopsticks,food,noodle,pho,ramen,soup
    🍝\tspaghetti\tfood,meatballs,pasta,restaurant
    🍠\troasted sweet potato\tfood
    🍢\toden\tfood,kebab,restaurant,seafood,skewer,stick
    🍣\tsushi\tfood
    🍤\tfried shrimp\tprawn,tempura
    🍥\tfish cake with swirl\tfood,pastry,restaurant
    🥮\tmoon cake\tautumn,festival,yuèbǐng
    🍡\tdango\tdessert,japanese,skewer,stick,sweet
    🥟\tdumpling\tempanada,gyōza,jiaozi,pierogi,potsticker
    🥠\tfortune cookie\tprophecy
    🥡\ttakeout box\tchopsticks,delivery,food,oyster,pail
    🍦\tsoft ice cream\tdessert,food,icecream,restaurant,serve,sweet
    🍧\tshaved ice\tdessert,restaurant,sweet
    🍨\tice cream\tdessert,food,restaurant,sweet
    🍩\tdoughnut\tbreakfast,dessert,donut,food,sweet
    🍪\tcookie\tchip,chocolate,dessert,sweet
    🎂\tbirthday cake\tbday,celebration,dessert,happy,pastry,sweet
    🍰\tshortcake\tdessert,pastry,slice,sweet
    🧁\tcupcake\tbakery,dessert,sprinkles,sugar,sweet,treat
    🥧\tpie\tapple,filling,fruit,meat,pastry,pumpkin
    🍫\tchocolate bar\tcandy,dessert,halloween,sweet,tooth
    🍬\tcandy\tcavities,dessert,halloween,restaurant,sweet,tooth
    🍭\tlollipop\tcandy,dessert,food,restaurant,sweet
    🍮\tcustard\tdessert,pudding,sweet
    🍯\thoney pot\tbarrel,bear,food,honeypot,jar,sweet
    🍼\tbaby bottle\tbabies,birth,born,drink,infant,milk
    🥛\tglass of milk\tdrink
    ☕\thot beverage\tcafe,caffeine,chai,coffee,drink,morning
    🫖\tteapot\tbrew,drink,food
    🍵\tteacup without handle\tbeverage,drink,oolong
    🍶\tsake\tbar,beverage,bottle,cup,drink,restaurant
    🍾\tbottle with popping cork\tbar,drink
    🍷\twine glass\talcohol,bar,beverage,booze,club,drink
    🍸\tcocktail glass\talcohol,bar,booze,club,drink,drinking
    🍹\ttropical drink\talcohol,bar,booze,club,cocktail,drinking
    🍺\tbeer mug\talcohol,ale,bar,booze,drink,drinking
    🍻\tclinking beer mugs\talcohol,bar,booze,bottoms,cheers,drinking
    🥂\tclinking glasses\tcelebrate,drink
    🥃\ttumbler glass\tliquor,scotch,shot,whiskey,whisky
    🫗\tpouring liquid\taccident,drink,empty,glass,oops,spill
    🥤\tcup with straw\tdrink,juice,malt,soda,soft,water
    🧋\tbubble tea\tboba,food,milk,pearl
    🧃\tbeverage box\tjuice,straw,sweet
    🧉\tmate\tdrink
    🧊\tice\tcold,cube,iceberg
    🥢\tchopsticks\thashi,jeotgarak,kuaizi
    🍽️\tfork and knife with plate\tcooking,dinner,eat
    🍴\tfork and knife\tbreakfast,breaky,cooking,cutlery,delicious,dinner
    🥄\tspoon\teat,tableware
    🔪\tkitchen knife\tchef,cooking,hocho,tool,weapon
    🫙\tjar\tcondiment,container,empty,nothing,sauce,store
    🏺\tamphora\taquarius,cooking,drink,jug,tool,weapon
    🌍\tglobe showing europe-africa\tearth,world
    🌎\tglobe showing americas\tearth,world
    🌏\tglobe showing asia-australia\tearth,world
    🌐\tglobe with meridians\tearth,internet,web,world,worldwide
    🗺️\tworld map\t
    🗾\tmap of japan\t
    🧭\tcompass\tdirection,magnetic,navigation,orienteering
    🏔️\tsnow-capped mountain\tcold
    ⛰️\tmountain\t
    🛘\tlandslide\tavalanche,danger,disaster,earthquake,mountain,mudslide
    🌋\tvolcano\teruption,mountain,nature
    🗻\tmount fuji\tmountain,nature
    🏕️\tcamping\t
    🏖️\tbeach with umbrella\t
    🏜️\tdesert\t
    🏝️\tdesert island\t
    🏞️\tnational park\t
    🏟️\tstadium\t
    🏛️\tclassical building\t
    🏗️\tbuilding construction\tcrane
    🧱\tbrick\tbricks,clay,mortar,wall
    🪨\trock\tboulder,heavy,solid,stone,tough
    🪵\twood\tlog,lumber,timber
    🛖\thut\thome,house,roundhouse,shelter,yurt
    🏘️\thouses\t
    🏚️\tderelict house\thome
    🏠\thouse\tbuilding,country,heart,home,ranch,settle
    🏡\thouse with garden\tbuilding,country,heart,home,ranch,settle
    🏢\toffice building\tcity,cubical,job
    🏣\tjapanese post office\tbuilding
    🏤\tpost office\tbuilding,european
    🏥\thospital\tbuilding,doctor,medicine
    🏦\tbank\tbuilding
    🏨\thotel\tbuilding
    🏩\tlove hotel\tbuilding
    🏪\tconvenience store\t24,building,hours
    🏫\tschool\tbuilding
    🏬\tdepartment store\tbuilding
    🏭\tfactory\tbuilding
    🏯\tjapanese castle\tbuilding
    🏰\tcastle\tbuilding,european
    💒\twedding\tchapel,hitched,nuptials,romance
    🗼\ttokyo tower\t
    🗽\tstatue of liberty\tnew,ny,nyc,york
    ⛪\tchurch\tbless,chapel,christian,cross,religion
    🕌\tmosque\tislam,masjid,muslim,religion
    🛕\thindu temple\t
    🕍\tsynagogue\tjew,jewish,judaism,religion,temple
    ⛩️\tshinto shrine\treligion
    🕋\tkaaba\thajj,islam,muslim,religion,umrah
    ⛲\tfountain\t
    ⛺\ttent\tcamping
    🌁\tfoggy\t
    🌃\tnight with stars\t
    🏙️\tcityscape\t
    🌄\tsunrise over mountains\tmorning
    🌅\tsunrise\tmorning,nature
    🌆\tcityscape at dusk\tbuilding,evening,landscape,sun,sunset
    🌇\tsunset\tbuilding,dusk
    🌉\tbridge at night\t
    ♨️\thot springs\thotsprings,steaming
    🎠\tcarousel horse\tentertainment
    🛝\tplayground slide\tamusement,park,playing,sliding,theme
    🎡\tferris wheel\tamusement,park,theme
    🎢\troller coaster\tamusement,park,theme
    💈\tbarber pole\tcut,fresh,haircut,shave
    🎪\tcircus tent\t
    🚂\tlocomotive\tcaboose,engine,railway,steam,train,trains
    🚃\trailway car\telectric,train,tram,travel,trolleybus
    🚄\thigh-speed train\trailway,shinkansen
    🚅\tbullet train\thigh-speed,nose,railway,shinkansen,speed,travel
    🚆\ttrain\tarrived,choo,railway
    🚇\tmetro\tsubway,travel
    🚈\tlight rail\tarrived,monorail,railway
    🚉\tstation\trailway,train
    🚊\ttram\ttrolleybus
    🚝\tmonorail\tvehicle
    🚞\tmountain railway\tcar,trip
    🚋\ttram car\tbus,trolley,trolleybus
    🚌\tbus\tschool,vehicle
    🚍\toncoming bus\tcars
    🚎\ttrolleybus\ttram
    🚐\tminibus\tdrive,van,vehicle
    🚑\tambulance\temergency,vehicle
    🚒\tfire engine\ttruck
    🚓\tpolice car\t5–0,cops,patrol
    🚔\toncoming police car\t
    🚕\ttaxi\tcab,cabbie,car,drive,vehicle,yellow
    🚖\toncoming taxi\tcab,cabbie,cars,drove,hail,yellow
    🚗\tautomobile\tcar,driving,vehicle
    🚘\toncoming automobile\tcar,cars,drove,vehicle
    🚙\tsport utility vehicle\tcar,drive,recreational,sportutility
    🛻\tpickup truck\tautomobile,car,flatbed,pick-up,transportation
    🚚\tdelivery truck\tcar,drive,vehicle
    🚛\tarticulated lorry\tcar,drive,move,semi,truck,vehicle
    🚜\ttractor\tvehicle
    🏎️\tracing car\tzoom
    🏍️\tmotorcycle\tracing
    🛵\tmotor scooter\t
    🦽\tmanual wheelchair\taccessibility
    🦼\tmotorized wheelchair\taccessibility
    🛺\tauto rickshaw\ttuk
    🚲\tbicycle\tbike,class,cycling,cyclist,gang,ride
    🛴\tkick scooter\t
    🛹\tskateboard\tskater,wheels
    🛼\troller skate\tblades,skates,sport
    🚏\tbus stop\tbusstop
    🛣️\tmotorway\thighway,road
    🛤️\trailway track\ttrain
    🛢️\toil drum\t
    ⛽\tfuel pump\tdiesel,fuelpump,gas,gasoline,station
    🛞\twheel\tcar,circle,tire,turn,vehicle
    🚨\tpolice car light\talarm,alert,beacon,emergency,revolving,siren
    🚥\thorizontal traffic light\tintersection,signal,stop,stoplight
    🚦\tvertical traffic light\tdrove,intersection,signal,stop,stoplight
    🛑\tstop sign\toctagonal
    🚧\tconstruction\tbarrier
    ⚓\tanchor\tship,tool
    🛟\tring buoy\tfloat,life,lifesaver,preserver,rescue,safety
    ⛵\tsailboat\tresort,sailing,sea,yacht
    🛶\tcanoe\tboat
    🚤\tspeedboat\tbillionaire,lake,luxury,millionaire,summer,travel
    🛳️\tpassenger ship\t
    ⛴️\tferry\tboat,passenger
    🛥️\tmotor boat\tmotorboat
    🚢\tship\tboat,passenger,travel
    ✈️\tairplane\taeroplane,fly,flying,jet,travel
    🛩️\tsmall airplane\taeroplane
    🛫\tairplane departure\taeroplane,check-in,departures
    🛬\tairplane arrival\taeroplane,arrivals,arriving,landing
    🪂\tparachute\thang-glide,parasail,skydive
    💺\tseat\tchair
    🚁\thelicopter\troflcopter,travel,vehicle
    🚟\tsuspension railway\t
    🚠\tmountain cableway\tgondola,lift,ski
    🚡\taerial tramway\tcable,car,gondola,ropeway
    🛰️\tsatellite\tspace
    🚀\trocket\tlaunch,rockets,space,travel
    🛸\tflying saucer\taliens,extra,terrestrial,ufo
    🛎️\tbellhop bell\thotel
    🧳\tluggage\tbag,packing,roller,suitcase,travel
    ⌛\thourglass done\tsand,time,timer
    ⏳\thourglass not done\tflowing,hours,sand,timer,waiting,yolo
    ⌚\twatch\tclock,time
    ⏰\talarm clock\thours,hrs,late,time,waiting
    ⏱️\tstopwatch\tclock,time
    ⏲️\ttimer clock\t
    🕰️\tmantelpiece clock\ttime
    🕛\ttwelve o’clock\t12,12:00,time
    🕧\ttwelve-thirty\t12,12:30,30,clock,time
    🕐\tone o’clock\t1,1:00,time
    🕜\tone-thirty\t1,1:30,30,clock,time
    🕑\ttwo o’clock\t2,2:00,time
    🕝\ttwo-thirty\t2,2:30,30,clock,time
    🕒\tthree o’clock\t3,3:00,time
    🕞\tthree-thirty\t3,3:30,30,clock,time
    🕓\tfour o’clock\t4,4:00,time
    🕟\tfour-thirty\t30,4,4:30,clock,time
    🕔\tfive o’clock\t5,5:00,time
    🕠\tfive-thirty\t30,5,5:30,clock,time
    🕕\tsix o’clock\t6,6:00,time
    🕡\tsix-thirty\t30,6,6:30,clock
    🕖\tseven o’clock\t0,7,7:00
    🕢\tseven-thirty\t30,7,7:30,clock
    🕗\teight o’clock\t8,8:00,time
    🕣\teight-thirty\t30,8,8:30,clock,time
    🕘\tnine o’clock\t9,9:00,time
    🕤\tnine-thirty\t30,9,9:30,clock,time
    🕙\tten o’clock\t0,10,10:00
    🕥\tten-thirty\t10,10:30,30,clock,time
    🕚\televen o’clock\t11,11:00,time
    🕦\televen-thirty\t11,11:30,30,clock,time
    🌑\tnew moon\tdark,space
    🌒\twaxing crescent moon\tdreams,space
    🌓\tfirst quarter moon\tspace
    🌔\twaxing gibbous moon\tspace
    🌕\tfull moon\tspace
    🌖\twaning gibbous moon\tspace
    🌗\tlast quarter moon\tspace
    🌘\twaning crescent moon\tspace
    🌙\tcrescent moon\tramadan,space
    🌚\tnew moon face\tspace
    🌛\tfirst quarter moon face\tspace
    🌜\tlast quarter moon face\tdreams
    🌡️\tthermometer\tweather
    ☀️\tsun\tbright,rays,space,sunny,weather
    🌝\tfull moon face\tbright
    🌞\tsun with face\tbeach,bright,day,heat,shine,sunny
    🪐\tringed planet\tsaturn,saturnine
    ⭐\tstar\tastronomy,medium,stars,white
    🌟\tglowing star\tglittery,night,shining,sparkle
    🌠\tshooting star\tfalling,night,space
    🌌\tmilky way\tspace
    ☁️\tcloud\tweather
    ⛅\tsun behind cloud\tcloudy,weather
    ⛈️\tcloud with lightning and rain\tthunder,thunderstorm
    🌤️\tsun behind small cloud\tweather
    🌥️\tsun behind large cloud\tweather
    🌦️\tsun behind rain cloud\tweather
    🌧️\tcloud with rain\tweather
    🌨️\tcloud with snow\tcold,weather
    🌩️\tcloud with lightning\tweather
    🌪️\ttornado\tcloud,weather,whirlwind
    🌫️\tfog\tcloud,weather
    🌬️\twind face\tblow,cloud
    🌀\tcyclone\tdizzy,hurricane,twister,typhoon,weather
    🌈\trainbow\tgay,genderqueer,glbt,glbtq,lesbian,lgbt
    🌂\tclosed umbrella\tclothing,rain
    ☂️\tumbrella\tclothing,rain
    ☔\tumbrella with rain drops\tclothing,weather
    ⛱️\tumbrella on ground\train,sun
    ⚡\thigh voltage\tdanger,electric,electricity,lightning,nature,thunder
    ❄️\tsnowflake\tcold,weather
    ☃️\tsnowman\tcold
    ⛄\tsnowman without snow\tcold
    ☄️\tcomet\tspace
    🔥\tfire\taf,burn,flame,hot,lit,litaf
    💧\tdroplet\tcold,comic,nature,sad,sweat,tear
    🌊\twater wave\tnature,ocean,surf,surfer,surfing
    🎃\tjack-o-lantern\tcelebration,halloween,pumpkin
    🎄\tchristmas tree\tcelebration
    🎆\tfireworks\tboom,celebration,entertainment,yolo
    🎇\tsparkler\tboom,celebration,fireworks
    🧨\tfirecracker\tdynamite,explosive,fireworks,light,pop,popping
    ✨\tsparkles\t*,magic,star
    🎈\tballoon\tbirthday,celebrate,celebration
    🎉\tparty popper\tawesome,birthday,celebrate,celebration,excited,hooray
    🎊\tconfetti ball\tcelebrate,celebration,party,woohoo
    🎋\ttanabata tree\tbanner,celebration,japanese
    🎍\tpine decoration\tbamboo,celebration,japanese,plant
    🎎\tjapanese dolls\tcelebration,festival
    🎏\tcarp streamer\tcelebration
    🎐\twind chime\tbell,celebration
    🎑\tmoon viewing ceremony\tcelebration
    🧧\tred envelope\tgift,good,hóngbāo,lai,luck,money
    🎀\tribbon\tcelebration
    🎁\twrapped gift\tbirthday,bow,box,celebration,christmas,present
    🎗️\treminder ribbon\tcelebration
    🎟️\tadmission tickets\t
    🎫\tticket\tadmission,stub
    🎖️\tmilitary medal\taward,celebration
    🏆\ttrophy\tchampion,champs,prize,slay,sport,victory
    🏅\tsports medal\taward,gold,winner
    🥇\t1st place medal\tfirst,gold
    🥈\t2nd place medal\tsecond,silver
    🥉\t3rd place medal\tbronze,third
    ⚽\tsoccer ball\tfootball,futbol,sport
    ⚾\tbaseball\tsport
    🥎\tsoftball\tglove,sports,underarm
    🏀\tbasketball\thoop,sport
    🏐\tvolleyball\tgame
    🏈\tamerican football\tbowl,sport,super
    🏉\trugby football\tsport
    🎾\ttennis\tball,racquet,sport
    🥏\tflying disc\tultimate
    🎳\tbowling\tball,game,sport,strike
    🏏\tcricket game\tball,bat
    🏑\tfield hockey\tball,game,stick
    🏒\tice hockey\tgame,puck,stick
    🥍\tlacrosse\tball,goal,sports,stick
    🏓\tping pong\tball,bat,game,paddle,pingpong,table
    🏸\tbadminton\tbirdie,game,racquet,shuttlecock
    🥊\tboxing glove\t
    🥋\tmartial arts uniform\tjudo,karate,taekwondo
    🥅\tgoal net\t
    ⛳\tflag in hole\tgolf,sport
    ⛸️\tice skate\tskating
    🎣\tfishing pole\tentertainment,sport
    🤿\tdiving mask\tscuba,snorkeling
    🎽\trunning shirt\tathletics,sash
    🎿\tskis\tsnow,sport
    🛷\tsled\tluge,sledge,sleigh,snow,toboggan
    🥌\tcurling stone\tgame,rock
    🎯\tbullseye\tdart,direct,entertainment,game,hit,target
    🪀\tyo-yo\tfluctuate,toy
    🪁\tkite\tfly,soar
    🔫\twater pistol\tgun,handgun,revolver,tool,weapon
    🎱\tpool 8 ball\t8ball,billiard,eight,game
    🔮\tcrystal ball\tfairy,fairytale,fantasy,fortune,future,magic
    🪄\tmagic wand\tmagician,witch,wizard
    🎮\tvideo game\tcontroller,entertainment
    🕹️\tjoystick\tgame,video,videogame
    🎰\tslot machine\tcasino,gamble,gambling,game,slots
    🎲\tgame die\tdice,entertainment
    🧩\tpuzzle piece\tclue,interlocking,jigsaw
    🧸\tteddy bear\tplaything,plush,stuffed,toy
    🪅\tpiñata\tcandy,celebrate,celebration,cinco,de,festive
    🪩\tmirror ball\tdance,disco,glitter,party
    🪆\tnesting dolls\tbabooshka,baboushka,babushka,matryoshka,russia
    ♠️\tspade suit\tcard,game
    ♥️\theart suit\tcard,emotion,game,hearts
    ♦️\tdiamond suit\tcard,game
    ♣️\tclub suit\tcard,clubs,game
    ♟️\tchess pawn\tdupe,expendable
    🃏\tjoker\tcard,game,wildcard
    🀄\tmahjong red dragon\tgame
    🎴\tflower playing cards\tgame,japanese
    🎭\tperforming arts\tactor,actress,entertainment,mask,theater,theatre
    🖼️\tframed picture\tart,museum,painting
    🎨\tartist palette\tartsy,arty,colorful,creative,entertainment,museum
    🧵\tthread\tneedle,sewing,spool,string
    🪡\tsewing needle\tembroidery,stitches,sutures,tailoring,thread
    🧶\tyarn\tball,crochet,knit
    🪢\tknot\tcord,rope,tangled,tie,twine,twist
    👓\tglasses\tclothing,eye,eyeglasses,eyewear
    🕶️\tsunglasses\tdark,eye,eyewear
    🥽\tgoggles\tdive,eye,protection,scuba,swimming,welding
    🥼\tlab coat\tclothes,doctor,dr,experiment,jacket,scientist
    🦺\tsafety vest\temergency
    👔\tnecktie\tclothing,employed,serious,shirt
    👕\tt-shirt\tblue,casual,clothes,clothing,collar,dressed
    👖\tjeans\tblue,casual,clothes,clothing,denim,dressed
    🧣\tscarf\tbundle,cold,neck,up
    🧤\tgloves\thand
    🧥\tcoat\tbrr,bundle,cold,jacket,up
    🧦\tsocks\tstocking
    👗\tdress\tclothes,clothing,dressed,fancy,shopping
    👘\tkimono\tclothing,comfortable
    🥻\tsari\tclothing,dress
    🩱\tone-piece swimsuit\tbathing
    🩲\tbriefs\tbathing,one-piece,suit,swimsuit,underwear
    🩳\tshorts\tbathing,pants,suit,swimsuit,underwear
    👙\tbikini\tbathing,beach,clothing,pool,suit,swim
    👚\twoman’s clothes\tblouse,clothing,collar,dress,dressed,lady
    🪭\tfolding hand fan\tclack,clap,cool,cooling,dance,flirt
    👛\tpurse\tclothes,clothing,coin,dress,fancy,handbag
    👜\thandbag\tclothes,clothing,dress,lady,purse,shopping
    👝\tclutch bag\tclothes,clothing,dress,handbag,pouch,purse
    🛍️\tshopping bags\thotel
    🎒\tbackpack\tbackpacking,bag,bookbag,education,rucksack,satchel
    🩴\tthong sandal\tbeach,flip,flop,sandals,shoe,thongs
    👞\tman’s shoe\tbrown,clothes,clothing,feet,foot,kick
    👟\trunning shoe\tathletic,clothes,clothing,fast,kick,shoes
    🥾\thiking boot\tbackpacking,brown,camping,outdoors,shoe
    🥿\tflat shoe\tballet,comfy,flats,slip-on,slipper
    👠\thigh-heeled shoe\tclothes,clothing,dress,fashion,heels,shoes
    👡\twoman’s sandal\tclothing,shoe
    🩰\tballet shoes\tdance
    👢\twoman’s boot\tclothes,clothing,dress,shoe,shoes,shopping
    🪮\thair pick\tafro,comb,groom
    👑\tcrown\tclothing,family,king,medieval,queen,royal
    👒\twoman’s hat\tclothes,clothing,garden,hats,party
    🎩\ttop hat\tclothes,clothing,fancy,formal,magic,tophat
    🎓\tgraduation cap\tcelebration,clothing,education,hat,scholar
    🧢\tbilled cap\tbaseball,bent,dad,hat
    🪖\tmilitary helmet\tarmy,soldier,war,warrior
    ⛑️\trescue worker’s helmet\taid,cross,face,hat
    📿\tprayer beads\tclothing,necklace,religion
    💄\tlipstick\tcosmetics,date,makeup
    💍\tring\tdiamond,engaged,engagement,married,romance,shiny
    💎\tgem stone\tdiamond,engagement,jewel,money,romance,wedding
    🔇\tmuted speaker\tquiet,silent,sound
    🔈\tspeaker low volume\tsoft,sound
    🔉\tspeaker medium volume\tsound
    🔊\tspeaker high volume\tloud,music,sound
    📢\tloudspeaker\taddress,communication,public,sound
    📣\tmegaphone\tcheering,sound
    📯\tpostal horn\t
    🔔\tbell\tbreak,church,sound
    🔕\tbell with slash\tforbidden,mute,no,not,prohibited,quiet
    🎼\tmusical score\tnote
    🎵\tmusical note\tsound
    🎶\tmusical notes\tsound
    🎙️\tstudio microphone\tmusic
    🎚️\tlevel slider\tmusic
    🎛️\tcontrol knobs\tmusic
    🎤\tmicrophone\tkaraoke,music,sing,sound
    🎧\theadphone\tearbud,sound
    📻\tradio\tentertainment,tbt,video
    🎷\tsaxophone\tinstrument,music
    🎺\ttrumpet\tinstrument,music
    🪊\ttrombone\tbrass,instrument,jazz,music,sad,slide
    🪗\taccordion\tbox,concertina,instrument,music,squeeze,squeezebox
    🎸\tguitar\tinstrument,music,strat
    🎹\tmusical keyboard\tinstrument,piano
    🎻\tviolin\tinstrument,music
    🪕\tbanjo\tmusic,stringed
    🥁\tdrum\tdrumsticks,music
    🪘\tlong drum\tbeat,conga,instrument,rhythm
    🪇\tmaracas\tcha,dance,instrument,music,party,percussion
    🪈\tflute\tband,fife,flautist,instrument,marching,music
    🪉\tharp\tcupid,instrument,love,music,orchestra
    📱\tmobile phone\tcell,communication,telephone
    📲\tmobile phone with arrow\tbuild,call,cell,communication,receive,telephone
    ☎️\ttelephone\t
    📞\ttelephone receiver\tcommunication,voip
    📟\tpager\tcommunication
    📠\tfax machine\tcommunication
    🔋\tbattery\t
    🪫\tlow battery\tdrained,electronic,energy,power
    🔌\telectric plug\telectricity
    💻\tlaptop\tcomputer,office,pc,personal
    🖥️\tdesktop computer\tmonitor
    🖨️\tprinter\tcomputer
    ⌨️\tkeyboard\tcomputer
    🖱️\tcomputer mouse\t
    🖲️\ttrackball\tcomputer
    💽\tcomputer disk\tminidisk,optical
    💾\tfloppy disk\tcomputer
    💿\toptical disk\tblu-ray,cd,computer,dvd
    📀\tdvd\tblu-ray,cd,computer,disk,optical
    🧮\tabacus\tcalculation,calculator
    🎥\tmovie camera\tbollywood,cinema,film,hollywood,record
    🎞️\tfilm frames\tcinema,movie
    📽️\tfilm projector\tcinema,movie,video
    🎬\tclapper board\taction,movie
    📺\ttelevision\ttv,video
    📷\tcamera\tphoto,selfie,snap,tbt,trip,video
    📸\tcamera with flash\tvideo
    📹\tvideo camera\tcamcorder,tbt
    📼\tvideocassette\told,school,tape,vcr,vhs
    🔍\tmagnifying glass tilted left\tlab,left-pointing,science,search,tool
    🔎\tmagnifying glass tilted right\tcontact,lab,right-pointing,science,search,tool
    🕯️\tcandle\tlight
    💡\tlight bulb\tcomic,electric,idea
    🔦\tflashlight\telectric,tool,torch
    🏮\tred paper lantern\tbar,light,restaurant
    🪔\tdiya lamp\tlight,oil
    📔\tnotebook with decorative cover\tdecorated,education,school,writing
    📕\tclosed book\teducation
    📖\topen book\teducation,fantasy,knowledge,library,novels,reading
    📗\tgreen book\teducation,fantasy,library,reading
    📘\tblue book\teducation,fantasy,library,reading
    📙\torange book\teducation,fantasy,library,reading
    📚\tbooks\teducation,fantasy,knowledge,library,novels,reading
    📓\tnotebook\t
    📒\tledger\tnotebook
    📃\tpage with curl\tdocument,paper
    📜\tscroll\tpaper
    📄\tpage facing up\tdocument,paper
    📰\tnewspaper\tcommunication
    🗞️\trolled-up newspaper\t
    📑\tbookmark tabs\tmarker
    🔖\tbookmark\t
    🏷️\tlabel\ttag
    🪙\tcoin\tdollar,euro,gold,metal,money,rich
    💰\tmoney bag\tbank,bet,billion,cash,cost,dollar
    🪎\ttreasure chest\tgem,gold,jewels,loot,money,prize
    💴\tyen banknote\tbill,currency,money
    💵\tdollar banknote\tbill,currency,money
    💶\teuro banknote\t100,bill,currency,money,rich
    💷\tpound banknote\tbill,billion,cash,currency,money,pounds
    💸\tmoney with wings\tbank,banknote,bill,billion,cash,dollar
    💳\tcredit card\tbank,cash,charge,money,pay
    🧾\treceipt\taccounting,bookkeeping,evidence,invoice,proof
    💹\tchart increasing with yen\tbank,currency,graph,growth,market,money
    ✉️\tenvelope\te-mail,email,letter
    📧\te-mail\temail,letter
    📨\tincoming envelope\tdelivering,e-mail,email,letter,mail,receive
    📩\tenvelope with arrow\tcommunication,down,e-mail,email,letter,mail
    📤\toutbox tray\temail,letter,mail,sent
    📥\tinbox tray\temail,letter,mail,receive,zero
    📦\tpackage\tbox,communication,delivery,parcel,shipping
    📫\tclosed mailbox with raised flag\tcommunication,postbox
    📪\tclosed mailbox with lowered flag\tpostbox
    📬\topen mailbox with raised flag\tpostbox
    📭\topen mailbox with lowered flag\tpostbox
    📮\tpostbox\tmail,mailbox
    🗳️\tballot box with ballot\t
    ✏️\tpencil\t
    ✒️\tblack nib\tpen
    🖋️\tfountain pen\t
    🖊️\tpen\tballpoint
    🖌️\tpaintbrush\tpainting
    🖍️\tcrayon\t
    📝\tmemo\tcommunication,media,notes,pencil
    💼\tbriefcase\toffice
    📁\tfile folder\t
    📂\topen file folder\t
    🗂️\tcard index dividers\t
    📅\tcalendar\tdate
    📆\ttear-off calendar\t
    🗒️\tspiral notepad\t
    🗓️\tspiral calendar\tpad
    📇\tcard index\told,rolodex,school
    📈\tchart increasing\tdata,graph,growth,right,trend,up
    📉\tchart decreasing\tdata,down,downward,graph,negative,trend
    📊\tbar chart\tdata,graph
    📋\tclipboard\tdo,list,notes
    📌\tpushpin\tcollage
    📍\tround pushpin\tlocation,map
    📎\tpaperclip\t
    🖇️\tlinked paperclips\t
    📏\tstraight ruler\tangle,edge,math,straightedge
    📐\ttriangular ruler\tangle,math,set,slide,triangle
    ✂️\tscissors\tcut,cutting,paper,tool
    🗃️\tcard file box\t
    🗄️\tfile cabinet\tfiling,paper
    🗑️\twastebasket\tcan,garbage,trash
    🔒\tlocked\tclosed,private
    🔓\tunlocked\tcracked,open
    🔏\tlocked with pen\tink,nib,privacy
    🔐\tlocked with key\tbike,closed,secure
    🔑\tkey\tkeys,lock,major,password,unlock
    🗝️\told key\tclue,lock
    🔨\thammer\thome,improvement,repairs,tool
    🪓\taxe\tchop,hatchet,split,wood
    ⛏️\tpick\thammer,mining,tool
    ⚒️\thammer and pick\ttool
    🛠️\thammer and wrench\tspanner,tool
    🗡️\tdagger\tknife,weapon
    ⚔️\tcrossed swords\tweapon
    💣\tbomb\tboom,comic,dangerous,explosion,hot
    🪃\tboomerang\trebound,repercussion,weapon
    🏹\tbow and arrow\tarcher,archery,sagittarius,tool,weapon,zodiac
    🛡️\tshield\tweapon
    🪚\tcarpentry saw\tcarpenter,cut,lumber,tool,trim
    🔧\twrench\thome,improvement,spanner,tool
    🪛\tscrewdriver\tflathead,handy,tool
    🔩\tnut and bolt\thome,improvement,tool
    ⚙️\tgear\tcog,cogwheel,tool
    🗜️\tclamp\tcompress,tool,vice
    ⚖️\tbalance scale\tjustice,libra,scales,tool,weight,zodiac
    🦯\twhite cane\taccessibility,blind,probing
    🔗\tlink\tlinks
    ⛓️‍💥\tbroken chain\tbreak,breaking,cuffs,freedom
    ⛓️\tchains\t
    🪝\thook\tcatch,crook,curve,ensnare,point,selling
    🧰\ttoolbox\tchest,mechanic,red
    🧲\tmagnet\tattraction,horseshoe,magnetic,negative,positive,shape
    🪜\tladder\tclimb,rung,step
    🪏\tshovel\tbury,dig,garden,hole,plant,scoop
    ⚗️\talembic\tchemistry,tool
    🧪\ttest tube\tchemist,chemistry,experiment,lab,science
    🧫\tpetri dish\tbacteria,biologist,biology,culture,lab
    🧬\tdna\tbiologist,evolution,gene,genetics,life
    🔬\tmicroscope\texperiment,lab,science,tool
    🔭\ttelescope\tcontact,extraterrestrial,science,tool
    📡\tsatellite antenna\taliens,contact,dish,science
    💉\tsyringe\tdoctor,flu,medicine,needle,shot,sick
    🩸\tdrop of blood\tbleed,donation,injury,medicine,menstruation
    💊\tpill\tdoctor,drugs,medicated,medicine,pills,sick
    🩹\tadhesive bandage\t
    🩼\tcrutch\taid,cane,disability,help,hurt,injured
    🩺\tstethoscope\tdoctor,heart,medicine
    🩻\tx-ray\tbones,doctor,medical,skeleton,skull,xray
    🚪\tdoor\tback,closet,front
    🛗\televator\taccessibility,hoist,lift
    🪞\tmirror\tmakeup,reflection,reflector,speculum
    🪟\twindow\tair,frame,fresh,opening,transparent,view
    🛏️\tbed\thotel,sleep
    🛋️\tcouch and lamp\thotel
    🪑\tchair\tseat,sit
    🚽\ttoilet\tbathroom
    🪠\tplunger\tcup,force,plumber,poop,suction,toilet
    🚿\tshower\twater
    🛁\tbathtub\t
    🪤\tmouse trap\tbait,cheese,lure,mousetrap,snare
    🪒\trazor\tsharp,shave
    🧴\tlotion bottle\tmoisturizer,shampoo,sunscreen
    🧷\tsafety pin\tdiaper,punk,rock
    🧹\tbroom\tcleaning,sweeping,witch
    🧺\tbasket\tfarming,laundry,picnic
    🧻\troll of paper\ttoilet,towels
    🪣\tbucket\tcask,pail,vat
    🧼\tsoap\tbar,bathing,clean,cleaning,lather,soapdish
    🫧\tbubbles\tburp,clean,floating,pearl,soap,underwater
    🪥\ttoothbrush\tbathroom,clean,dental,hygiene,teeth,toiletry
    🧽\tsponge\tabsorbing,cleaning,porous,soak
    🧯\tfire extinguisher\tquench
    🛒\tshopping cart\ttrolley
    🚬\tcigarette\tsmoking
    ⚰️\tcoffin\tdead,death,vampire
    🪦\theadstone\tcemetery,dead,grave,graveyard,memorial,rip
    ⚱️\tfuneral urn\tashes,death
    🧿\tnazar amulet\tbead,blue,charm,evil-eye,talisman
    🪬\thamsa\tamulet,fatima,fortune,guide,hand,mary
    🗿\tmoai\tface,moyai,statue,stoneface,travel
    🪧\tplacard\tdemonstration,notice,picket,plaque,protest,sign
    🪪\tidentification card\tcredentials,document,license,security
    🏧\tatm sign\tautomated,bank,cash,money,teller
    🚮\tlitter in bin sign\tlitterbin
    🚰\tpotable water\tdrinking
    ♿\twheelchair symbol\taccess,handicap
    🚹\tmen’s room\tbathroom,lavatory,man,restroom,toilet,wc
    🚺\twomen’s room\tbathroom,lavatory,restroom,toilet,wc,woman
    🚻\trestroom\tbathroom,lavatory,toilet,wc
    🚼\tbaby symbol\tchanging
    🚾\twater closet\tbathroom,lavatory,restroom,toilet,wc
    🛂\tpassport control\t
    🛃\tcustoms\tpacking
    🛄\tbaggage claim\tarrived,bags,case,checked,journey,packing
    🛅\tleft luggage\tbaggage,case,locker
    ⚠️\twarning\tcaution
    🚸\tchildren crossing\tpedestrian,traffic
    ⛔\tno entry\tdo,fail,forbidden,not,pass,prohibited
    🚫\tprohibited\tentry,forbidden,no,not,smoke
    🚳\tno bicycles\tbike,forbidden,not,prohibited
    🚭\tno smoking\tforbidden,not,prohibited,smoke
    🚯\tno littering\tforbidden,not,prohibited
    🚱\tnon-potable water\tdry,non-drinking,prohibited
    🚷\tno pedestrians\tforbidden,not,prohibited
    📵\tno mobile phones\tcell,forbidden,not,prohibited,telephone
    🔞\tno one under eighteen\t18,age,forbidden,not,prohibited,restriction
    ☢️\tradioactive\tsign
    ☣️\tbiohazard\tsign
    ⬆️\tup arrow\tcardinal,direction,north
    ↗️\tup-right arrow\tdirection,intercardinal,northeast
    ➡️\tright arrow\tcardinal,direction,east
    ↘️\tdown-right arrow\tdirection,intercardinal,southeast
    ⬇️\tdown arrow\tcardinal,direction,south
    ↙️\tdown-left arrow\tdirection,intercardinal,southwest
    ⬅️\tleft arrow\tcardinal,direction,west
    ↖️\tup-left arrow\tdirection,intercardinal,northwest
    ↕️\tup-down arrow\t
    ↔️\tleft-right arrow\t
    ↩️\tright arrow curving left\t
    ↪️\tleft arrow curving right\t
    ⤴️\tright arrow curving up\t
    ⤵️\tright arrow curving down\t
    🔃\tclockwise vertical arrows\trefresh,reload
    🔄\tcounterclockwise arrows button\tagain,anticlockwise,deja,refresh,rewindershins,vu
    🔙\tback arrow\t
    🔚\tend arrow\t
    🔛\ton! arrow\tmark
    🔜\tsoon arrow\tbrb,omw
    🔝\ttop arrow\thomie,up
    🛐\tplace of worship\tpray,religion
    ⚛️\tatom symbol\tatheist
    🕉️\tom\thindu,religion
    ✡️\tstar of david\tjew,jewish,judaism,religion
    ☸️\twheel of dharma\tbuddhist,religion
    ☯️\tyin yang\tdifficult,lives,religion,tao,taoist,total
    ✝️\tlatin cross\tchrist,christian,religion
    ☦️\torthodox cross\tchristian,religion
    ☪️\tstar and crescent\tislam,muslim,ramadan,religion
    ☮️\tpeace symbol\thealing,peaceful
    🕎\tmenorah\tcandelabrum,candlestick,hanukkah,jewish,judaism,religion
    🔯\tdotted six-pointed star\tfortune,jewish,judaism
    🪯\tkhanda\tdeg,fateh,khalsa,religion,sikh,sikhism
    ♈\taries\thoroscope,ram,zodiac
    ♉\ttaurus\tbull,horoscope,ox,zodiac
    ♊\tgemini\thoroscope,twins,zodiac
    ♋\tcancer\tcrab,horoscope,zodiac
    ♌\tleo\thoroscope,lion,zodiac
    ♍\tvirgo\thoroscope,zodiac
    ♎\tlibra\tbalance,horoscope,justice,scales,zodiac
    ♏\tscorpio\thoroscope,scorpion,scorpius,zodiac
    ♐\tsagittarius\tarcher,horoscope,zodiac
    ♑\tcapricorn\tgoat,horoscope,zodiac
    ♒\taquarius\tbearer,horoscope,water,zodiac
    ♓\tpisces\tfish,horoscope,zodiac
    ⛎\tophiuchus\tbearer,serpent,snake,zodiac
    🔀\tshuffle tracks button\tarrow,crossed
    🔁\trepeat button\tarrow,clockwise
    🔂\trepeat single button\tarrow,clockwise,once
    ▶️\tplay button\tarrow,right,triangle
    ⏩\tfast-forward button\tarrow,double
    ⏭️\tnext track button\tarrow,scene,triangle
    ⏯️\tplay or pause button\tarrow,right,triangle
    ◀️\treverse button\tarrow,left,triangle
    ⏪\tfast reverse button\tarrow,double,rewind
    ⏮️\tlast track button\tarrow,previous,scene,triangle
    🔼\tupwards button\tarrow,red
    ⏫\tfast up button\tarrow,double
    🔽\tdownwards button\tarrow,red
    ⏬\tfast down button\tarrow,double
    ⏸️\tpause button\tbar,double,vertical
    ⏹️\tstop button\tsquare
    ⏺️\trecord button\tcircle
    ⏏️\teject button\t
    🎦\tcinema\tcamera,film,movie
    🔅\tdim button\tbrightness,low
    🔆\tbright button\tbrightness,light
    📶\tantenna bars\tcell,communication,mobile,phone,signal,telephone
    🛜\twireless\tbroadband,computer,connectivity,hotspot,internet,network
    📳\tvibration mode\tcell,communication,mobile,phone,telephone
    📴\tmobile phone off\tcell,telephone
    ♀️\tfemale sign\twoman
    ♂️\tmale sign\tman
    ⚧️\ttransgender symbol\t
    ✖️\tmultiply\t×,cancel,multiplication,sign,x
    ➕\tplus\t+
    ➖\tminus\t-,−,heavy,math,sign
    ➗\tdivide\t÷,division,heavy,math,sign
    🟰\theavy equals sign\tanswer,equality,math
    ♾️\tinfinity\tforever,unbounded,universal
    ‼️\tdouble exclamation mark\t!,!!,bangbang,punctuation
    ⁉️\texclamation question mark\t!,!?,?,interrobang,punctuation
    ❓\tred question mark\t?,punctuation
    ❔\twhite question mark\t?,outlined,punctuation
    ❕\twhite exclamation mark\t!,outlined,punctuation
    ❗\tred exclamation mark\t!,punctuation
    〰️\twavy dash\tpunctuation
    💱\tcurrency exchange\tbank,money
    💲\theavy dollar sign\tbillion,cash,charge,currency,million,money
    ⚕️\tmedical symbol\taesculapius,medicine,staff
    ♻️\trecycling symbol\trecycle
    ⚜️\tfleur-de-lis\tknights
    🔱\ttrident emblem\tanchor,poseidon,ship,tool
    📛\tname badge\t
    🔰\tjapanese symbol for beginner\tchevron,green,leaf,tool,yellow
    ⭕\thollow red circle\theavy,large
    ✅\tcheck mark button\t✓,checked,checkmark,complete,completed,done
    ☑️\tcheck box with check\t✓,ballot,checked,done,off,tick
    ✔️\tcheck mark\t✓,checked,checkmark,done,heavy,tick
    ❌\tcross mark\t×,cancel,multiplication,multiply,x
    ❎\tcross mark button\t×,multiplication,multiply,square,x
    ➰\tcurly loop\t
    ➿\tdouble curly loop\t
    〽️\tpart alternation mark\t
    ✳️\teight-spoked asterisk\t*
    ✴️\teight-pointed star\t*
    ❇️\tsparkle\t*
    ©️\tcopyright\t
    ®️\tregistered\t
    ™️\ttrade mark\ttm,trademark
    🫟\tsplatter\tdrip,holi,ink,liquid,mess,paint
    #️⃣\tkeycap: #\t
    *️⃣\tkeycap: *\t
    0️⃣\tkeycap: 0\tzero
    1️⃣\tkeycap: 1\tone
    2️⃣\tkeycap: 2\ttwo
    3️⃣\tkeycap: 3\tthree
    4️⃣\tkeycap: 4\tfour
    5️⃣\tkeycap: 5\tfive
    6️⃣\tkeycap: 6\tsix
    7️⃣\tkeycap: 7\tseven
    8️⃣\tkeycap: 8\teight
    9️⃣\tkeycap: 9\tnine
    🔟\tkeycap: 10\t
    🔠\tinput latin uppercase\tabcd,letters
    🔡\tinput latin lowercase\tabcd,letters
    🔢\tinput numbers\t1234
    🔣\tinput symbols\t&,%,♪,〒
    🔤\tinput latin letters\tabc,alphabet
    🅰️\ta button (blood type)\t
    🆎\tab button (blood type)\t
    🅱️\tb button (blood type)\t
    🆑\tcl button\t
    🆒\tcool button\t
    🆓\tfree button\t
    ℹ️\tinformation\t
    🆔\tid button\tidentity
    Ⓜ️\tcircled m\t
    🆕\tnew button\t
    🆖\tng button\t
    🅾️\to button (blood type)\t
    🆗\tok button\tokay
    🅿️\tp button\tparking
    🆘\tsos button\thelp
    🆙\tup! button\tmark
    🆚\tvs button\tversus
    🈁\tjapanese “here” button\tkatakana
    🈂️\tjapanese “service charge” button\tkatakana
    🈷️\tjapanese “monthly amount” button\tideograph
    🈶\tjapanese “not free of charge” button\tideograph
    🈯\tjapanese “reserved” button\tideograph
    🉐\tjapanese “bargain” button\tideograph
    🈹\tjapanese “discount” button\tideograph
    🈚\tjapanese “free of charge” button\tideograph
    🈲\tjapanese “prohibited” button\tideograph
    🉑\tjapanese “acceptable” button\tideograph
    🈸\tjapanese “application” button\tideograph
    🈴\tjapanese “passing grade” button\tideograph
    🈳\tjapanese “vacancy” button\tideograph
    ㊗️\tjapanese “congratulations” button\tideograph
    ㊙️\tjapanese “secret” button\tideograph
    🈺\tjapanese “open for business” button\tideograph
    🈵\tjapanese “no vacancy” button\tideograph
    🔴\tred circle\tgeometric
    🟠\torange circle\t
    🟡\tyellow circle\t
    🟢\tgreen circle\t
    🔵\tblue circle\tgeometric
    🟣\tpurple circle\t
    🟤\tbrown circle\t
    ⚫\tblack circle\tgeometric
    ⚪\twhite circle\tgeometric
    🟥\tred square\tcard,penalty
    🟧\torange square\t
    🟨\tyellow square\tcard,penalty
    🟩\tgreen square\t
    🟦\tblue square\t
    🟪\tpurple square\t
    🟫\tbrown square\t
    ⬛\tblack large square\tgeometric
    ⬜\twhite large square\tgeometric
    ◼️\tblack medium square\tgeometric
    ◻️\twhite medium square\tgeometric
    ◾\tblack medium-small square\tgeometric
    ◽\twhite medium-small square\tgeometric
    ▪️\tblack small square\tgeometric
    ▫️\twhite small square\tgeometric
    🔶\tlarge orange diamond\tgeometric
    🔷\tlarge blue diamond\tgeometric
    🔸\tsmall orange diamond\tgeometric
    🔹\tsmall blue diamond\tgeometric
    🔺\tred triangle pointed up\tgeometric
    🔻\tred triangle pointed down\tgeometric
    💠\tdiamond with a dot\tcomic,geometric
    🔘\tradio button\tgeometric
    🔳\twhite square button\tgeometric,outlined
    🔲\tblack square button\tgeometric
    🏁\tchequered flag\tcheckered,finish,flags,game,race,racing
    🚩\ttriangular flag\tconstruction,golf,post
    🎌\tcrossed flags\tcelebration,japanese
    🏴\tblack flag\twaving
    🏳️\twhite flag\twaving
    🏳️‍🌈\trainbow flag\tbisexual,gay,genderqueer,glbt,glbtq,lesbian
    🏳️‍⚧️\ttransgender flag\tblue,light,pink,white
    🏴‍☠️\tpirate flag\tjolly,plunder,roger,treasure
    🇦🇨\tflag: ascension island\t
    🇦🇩\tflag: andorra\t
    🇦🇪\tflag: united arab emirates\t
    🇦🇫\tflag: afghanistan\t
    🇦🇬\tflag: antigua & barbuda\t
    🇦🇮\tflag: anguilla\t
    🇦🇱\tflag: albania\t
    🇦🇲\tflag: armenia\t
    🇦🇴\tflag: angola\t
    🇦🇶\tflag: antarctica\t
    🇦🇷\tflag: argentina\t
    🇦🇸\tflag: american samoa\t
    🇦🇹\tflag: austria\t
    🇦🇺\tflag: australia\t
    🇦🇼\tflag: aruba\t
    🇦🇽\tflag: åland islands\t
    🇦🇿\tflag: azerbaijan\t
    🇧🇦\tflag: bosnia & herzegovina\t
    🇧🇧\tflag: barbados\t
    🇧🇩\tflag: bangladesh\t
    🇧🇪\tflag: belgium\t
    🇧🇫\tflag: burkina faso\t
    🇧🇬\tflag: bulgaria\t
    🇧🇭\tflag: bahrain\t
    🇧🇮\tflag: burundi\t
    🇧🇯\tflag: benin\t
    🇧🇱\tflag: st. barthélemy\t
    🇧🇲\tflag: bermuda\t
    🇧🇳\tflag: brunei\t
    🇧🇴\tflag: bolivia\t
    🇧🇶\tflag: caribbean netherlands\t
    🇧🇷\tflag: brazil\t
    🇧🇸\tflag: bahamas\t
    🇧🇹\tflag: bhutan\t
    🇧🇻\tflag: bouvet island\t
    🇧🇼\tflag: botswana\t
    🇧🇾\tflag: belarus\t
    🇧🇿\tflag: belize\t
    🇨🇦\tflag: canada\t
    🇨🇨\tflag: cocos (keeling) islands\t
    🇨🇩\tflag: congo - kinshasa\t
    🇨🇫\tflag: central african republic\t
    🇨🇬\tflag: congo - brazzaville\t
    🇨🇭\tflag: switzerland\t
    🇨🇮\tflag: côte d’ivoire\t
    🇨🇰\tflag: cook islands\t
    🇨🇱\tflag: chile\t
    🇨🇲\tflag: cameroon\t
    🇨🇳\tflag: china\t
    🇨🇴\tflag: colombia\t
    🇨🇵\tflag: clipperton island\t
    🇨🇶\tflag: sark\t
    🇨🇷\tflag: costa rica\t
    🇨🇺\tflag: cuba\t
    🇨🇻\tflag: cape verde\t
    🇨🇼\tflag: curaçao\t
    🇨🇽\tflag: christmas island\t
    🇨🇾\tflag: cyprus\t
    🇨🇿\tflag: czechia\t
    🇩🇪\tflag: germany\t
    🇩🇬\tflag: diego garcia\t
    🇩🇯\tflag: djibouti\t
    🇩🇰\tflag: denmark\t
    🇩🇲\tflag: dominica\t
    🇩🇴\tflag: dominican republic\t
    🇩🇿\tflag: algeria\t
    🇪🇦\tflag: ceuta & melilla\t
    🇪🇨\tflag: ecuador\t
    🇪🇪\tflag: estonia\t
    🇪🇬\tflag: egypt\t
    🇪🇭\tflag: western sahara\t
    🇪🇷\tflag: eritrea\t
    🇪🇸\tflag: spain\t
    🇪🇹\tflag: ethiopia\t
    🇪🇺\tflag: european union\t
    🇫🇮\tflag: finland\t
    🇫🇯\tflag: fiji\t
    🇫🇰\tflag: falkland islands\t
    🇫🇲\tflag: micronesia\t
    🇫🇴\tflag: faroe islands\t
    🇫🇷\tflag: france\t
    🇬🇦\tflag: gabon\t
    🇬🇧\tflag: united kingdom\t
    🇬🇩\tflag: grenada\t
    🇬🇪\tflag: georgia\t
    🇬🇫\tflag: french guiana\t
    🇬🇬\tflag: guernsey\t
    🇬🇭\tflag: ghana\t
    🇬🇮\tflag: gibraltar\t
    🇬🇱\tflag: greenland\t
    🇬🇲\tflag: gambia\t
    🇬🇳\tflag: guinea\t
    🇬🇵\tflag: guadeloupe\t
    🇬🇶\tflag: equatorial guinea\t
    🇬🇷\tflag: greece\t
    🇬🇸\tflag: south georgia & south sandwich islands\t
    🇬🇹\tflag: guatemala\t
    🇬🇺\tflag: guam\t
    🇬🇼\tflag: guinea-bissau\t
    🇬🇾\tflag: guyana\t
    🇭🇰\tflag: hong kong sar china\t
    🇭🇲\tflag: heard & mcdonald islands\t
    🇭🇳\tflag: honduras\t
    🇭🇷\tflag: croatia\t
    🇭🇹\tflag: haiti\t
    🇭🇺\tflag: hungary\t
    🇮🇨\tflag: canary islands\t
    🇮🇩\tflag: indonesia\t
    🇮🇪\tflag: ireland\t
    🇮🇱\tflag: israel\t
    🇮🇲\tflag: isle of man\t
    🇮🇳\tflag: india\t
    🇮🇴\tflag: british indian ocean territory\t
    🇮🇶\tflag: iraq\t
    🇮🇷\tflag: iran\t
    🇮🇸\tflag: iceland\t
    🇮🇹\tflag: italy\t
    🇯🇪\tflag: jersey\t
    🇯🇲\tflag: jamaica\t
    🇯🇴\tflag: jordan\t
    🇯🇵\tflag: japan\t
    🇰🇪\tflag: kenya\t
    🇰🇬\tflag: kyrgyzstan\t
    🇰🇭\tflag: cambodia\t
    🇰🇮\tflag: kiribati\t
    🇰🇲\tflag: comoros\t
    🇰🇳\tflag: st. kitts & nevis\t
    🇰🇵\tflag: north korea\t
    🇰🇷\tflag: south korea\t
    🇰🇼\tflag: kuwait\t
    🇰🇾\tflag: cayman islands\t
    🇰🇿\tflag: kazakhstan\t
    🇱🇦\tflag: laos\t
    🇱🇧\tflag: lebanon\t
    🇱🇨\tflag: st. lucia\t
    🇱🇮\tflag: liechtenstein\t
    🇱🇰\tflag: sri lanka\t
    🇱🇷\tflag: liberia\t
    🇱🇸\tflag: lesotho\t
    🇱🇹\tflag: lithuania\t
    🇱🇺\tflag: luxembourg\t
    🇱🇻\tflag: latvia\t
    🇱🇾\tflag: libya\t
    🇲🇦\tflag: morocco\t
    🇲🇨\tflag: monaco\t
    🇲🇩\tflag: moldova\t
    🇲🇪\tflag: montenegro\t
    🇲🇫\tflag: st. martin\t
    🇲🇬\tflag: madagascar\t
    🇲🇭\tflag: marshall islands\t
    🇲🇰\tflag: north macedonia\t
    🇲🇱\tflag: mali\t
    🇲🇲\tflag: myanmar (burma)\t
    🇲🇳\tflag: mongolia\t
    🇲🇴\tflag: macao sar china\t
    🇲🇵\tflag: northern mariana islands\t
    🇲🇶\tflag: martinique\t
    🇲🇷\tflag: mauritania\t
    🇲🇸\tflag: montserrat\t
    🇲🇹\tflag: malta\t
    🇲🇺\tflag: mauritius\t
    🇲🇻\tflag: maldives\t
    🇲🇼\tflag: malawi\t
    🇲🇽\tflag: mexico\t
    🇲🇾\tflag: malaysia\t
    🇲🇿\tflag: mozambique\t
    🇳🇦\tflag: namibia\t
    🇳🇨\tflag: new caledonia\t
    🇳🇪\tflag: niger\t
    🇳🇫\tflag: norfolk island\t
    🇳🇬\tflag: nigeria\t
    🇳🇮\tflag: nicaragua\t
    🇳🇱\tflag: netherlands\t
    🇳🇴\tflag: norway\t
    🇳🇵\tflag: nepal\t
    🇳🇷\tflag: nauru\t
    🇳🇺\tflag: niue\t
    🇳🇿\tflag: new zealand\t
    🇴🇲\tflag: oman\t
    🇵🇦\tflag: panama\t
    🇵🇪\tflag: peru\t
    🇵🇫\tflag: french polynesia\t
    🇵🇬\tflag: papua new guinea\t
    🇵🇭\tflag: philippines\t
    🇵🇰\tflag: pakistan\t
    🇵🇱\tflag: poland\t
    🇵🇲\tflag: st. pierre & miquelon\t
    🇵🇳\tflag: pitcairn islands\t
    🇵🇷\tflag: puerto rico\t
    🇵🇸\tflag: palestinian territories\t
    🇵🇹\tflag: portugal\t
    🇵🇼\tflag: palau\t
    🇵🇾\tflag: paraguay\t
    🇶🇦\tflag: qatar\t
    🇷🇪\tflag: réunion\t
    🇷🇴\tflag: romania\t
    🇷🇸\tflag: serbia\t
    🇷🇺\tflag: russia\t
    🇷🇼\tflag: rwanda\t
    🇸🇦\tflag: saudi arabia\t
    🇸🇧\tflag: solomon islands\t
    🇸🇨\tflag: seychelles\t
    🇸🇩\tflag: sudan\t
    🇸🇪\tflag: sweden\t
    🇸🇬\tflag: singapore\t
    🇸🇭\tflag: st. helena\t
    🇸🇮\tflag: slovenia\t
    🇸🇯\tflag: svalbard & jan mayen\t
    🇸🇰\tflag: slovakia\t
    🇸🇱\tflag: sierra leone\t
    🇸🇲\tflag: san marino\t
    🇸🇳\tflag: senegal\t
    🇸🇴\tflag: somalia\t
    🇸🇷\tflag: suriname\t
    🇸🇸\tflag: south sudan\t
    🇸🇹\tflag: são tomé & príncipe\t
    🇸🇻\tflag: el salvador\t
    🇸🇽\tflag: sint maarten\t
    🇸🇾\tflag: syria\t
    🇸🇿\tflag: eswatini\t
    🇹🇦\tflag: tristan da cunha\t
    🇹🇨\tflag: turks & caicos islands\t
    🇹🇩\tflag: chad\t
    🇹🇫\tflag: french southern territories\t
    🇹🇬\tflag: togo\t
    🇹🇭\tflag: thailand\t
    🇹🇯\tflag: tajikistan\t
    🇹🇰\tflag: tokelau\t
    🇹🇱\tflag: timor-leste\t
    🇹🇲\tflag: turkmenistan\t
    🇹🇳\tflag: tunisia\t
    🇹🇴\tflag: tonga\t
    🇹🇷\tflag: türkiye\t
    🇹🇹\tflag: trinidad & tobago\t
    🇹🇻\tflag: tuvalu\t
    🇹🇼\tflag: taiwan\t
    🇹🇿\tflag: tanzania\t
    🇺🇦\tflag: ukraine\t
    🇺🇬\tflag: uganda\t
    🇺🇲\tflag: u.s. outlying islands\t
    🇺🇳\tflag: united nations\t
    🇺🇸\tflag: united states\t
    🇺🇾\tflag: uruguay\t
    🇺🇿\tflag: uzbekistan\t
    🇻🇦\tflag: vatican city\t
    🇻🇨\tflag: st. vincent & grenadines\t
    🇻🇪\tflag: venezuela\t
    🇻🇬\tflag: british virgin islands\t
    🇻🇮\tflag: u.s. virgin islands\t
    🇻🇳\tflag: vietnam\t
    🇻🇺\tflag: vanuatu\t
    🇼🇫\tflag: wallis & futuna\t
    🇼🇸\tflag: samoa\t
    🇽🇰\tflag: kosovo\t
    🇾🇪\tflag: yemen\t
    🇾🇹\tflag: mayotte\t
    🇿🇦\tflag: south africa\t
    🇿🇲\tflag: zambia\t
    🇿🇼\tflag: zimbabwe\t
    🏴󠁧󠁢󠁥󠁮󠁧󠁿\tflag: england\t
    🏴󠁧󠁢󠁳󠁣󠁴󠁿\tflag: scotland\t
    🏴󠁧󠁢󠁷󠁬󠁳󠁿\tflag: wales\t
    """
}
