#!/usr/bin/env python3
"""Regenerates Vibeshed/Modules/Emoji/EmojiData.swift.

Sources:
  - Unicode emoji-test.txt (fully-qualified entries, skin-tone variants excluded)
  - CLDR en annotations (search keywords)

Run from the repo root:  python3 scripts/generate-emoji.py
"""

import json
import re
import urllib.request

EMOJI_TEST_URL = "https://unicode.org/Public/emoji/latest/emoji-test.txt"
CLDR_URL = (
    "https://raw.githubusercontent.com/unicode-org/cldr-json/main/"
    "cldr-json/cldr-annotations-full/annotations/en/annotations.json"
)
OUT = "Vibeshed/Modules/Emoji/EmojiData.swift"
MAX_KEYWORDS = 6

ENTRY_RE = re.compile(
    r"^[0-9A-F ]+;\s*fully-qualified\s*#\s*(\S+)\s+E[\d.]+\s+(.+)$"
)


def fetch(url):
    with urllib.request.urlopen(url) as response:
        return response.read().decode("utf-8")


def clean(text):
    """Keep the TSV safe inside a Swift multiline string literal."""
    return text.replace("\\", "").replace('"""', "").replace("\t", " ").strip()


def main():
    emoji_test = fetch(EMOJI_TEST_URL)
    annotations = json.loads(fetch(CLDR_URL))["annotations"]["annotations"]

    lines = []
    for line in emoji_test.splitlines():
        match = ENTRY_RE.match(line.strip())
        if not match:
            continue
        char, name = match.groups()
        if "skin tone" in name:
            continue
        name = clean(name.lower())
        lookup = annotations.get(char) or annotations.get(char.replace("\ufe0f", "")) or {}
        keywords = [clean(k.lower()) for k in lookup.get("default", [])]
        keywords = [k for k in keywords if k and k not in name][:MAX_KEYWORDS]
        lines.append("    " + "\\t".join([char, name, ",".join(keywords)]))

    header = f"""\
// Generated by scripts/generate-emoji.py — do not edit by hand.
// Sources: Unicode emoji-test.txt (fully-qualified, skin tones excluded)
// + CLDR en annotations for search keywords. {len(lines)} entries.
// Excluded from SwiftLint via .swiftlint.yml.

enum EmojiData {{
    /// One emoji per line: char \\t name \\t comma-separated keywords.
    static let tsv = \"\"\"
"""
    footer = '    """\n}\n'
    with open(OUT, "w", encoding="utf-8") as out:
        out.write(header)
        out.write("\n".join(lines))
        out.write("\n")
        out.write(footer)
    print(f"Wrote {OUT}: {len(lines)} emoji")


if __name__ == "__main__":
    main()
