import Foundation
@testable import Vibeshed
import XCTest

final class NeovimThemeTargetTests: XCTestCase {
    private let palette = (try? ThemePalette.resolve(BuiltInThemes.dracula.colors, mode: .dark))
        ?? ThemePalette(mode: .dark, colors: [:])

    func testColorschemeCoversEditorSyntaxAndTerminal() {
        let scheme = NeovimThemeBuilder.colorscheme(palette, themeName: "Dracula")
        XCTAssertTrue(scheme.hasPrefix("-- Generated by Vibeshed from the \"Dracula\" theme"))
        XCTAssertTrue(scheme.contains("vim.g.colors_name = \"vibeshed\""))
        XCTAssertTrue(scheme.contains("vim.o.background = \"dark\""))
        let normal = "hl(\"Normal\", { fg = \"\(palette.foreground.hex)\", bg = \"\(palette.background.hex)\" })"
        XCTAssertTrue(scheme.contains(normal))
        XCTAssertTrue(scheme.contains("hl(\"String\", { fg = \"\(palette.green.hex)\" })"))
        XCTAssertTrue(scheme.contains("hl(\"@lsp.type.parameter\", { link = \"@variable.parameter\" })"))
        XCTAssertTrue(scheme.contains("hl(\"SpellBad\", { sp = \"\(palette.red.hex)\", undercurl = true })"))
        XCTAssertTrue(scheme.contains("vim.g.terminal_color_15 = \"\(palette.ansi[15].hex)\""))
    }

    func testEveryGroupIsDefinedOnceAndLinksResolve() {
        let highlights = NeovimThemeBuilder.highlights(palette)
        let groups = highlights.map(\.group)
        XCTAssertEqual(groups.count, Set(groups).count, "duplicate groups")
        let defined = Set(groups)
        for link in highlights.compactMap(\.link) {
            XCTAssertTrue(defined.contains(link), "\(link) is linked but never defined")
        }
    }

    func testAliasLoadsSchemeUnderVibeshedName() {
        let alias = NeovimThemeBuilder.alias("tokyo\"night", mode: .light, themeName: "Tokyo Night")
        XCTAssertTrue(alias.contains("pcall(vim.cmd.colorscheme, \"tokyo\\\"night\")"))
        XCTAssertTrue(alias.contains("vim.o.background = \"light\""))
        XCTAssertTrue(alias.hasSuffix("vim.g.colors_name = \"vibeshed\"\n"))
    }

    func testLineBreaksStayInsideStringsAndComments() {
        XCTAssertEqual(NeovimThemeBuilder.luaString("a\\b\r\nc"), #""a\\b\r\nc""#)
        let alias = NeovimThemeBuilder.alias("tokyo\nnight", mode: .dark, themeName: "Two\nLines")
        XCTAssertTrue(alias.hasPrefix("-- Generated by Vibeshed from the \"Two Lines\" theme"))
        XCTAssertTrue(alias.contains(#"pcall(vim.cmd.colorscheme, "tokyo\nnight")"#))
    }

    func testReloadCommandQuotesAndOnlyTouchesVibeshedEditors() {
        let command = NeovimTarget.reloadCommand(nvim: "/opt/homebrew/bin/nvim", sockets: ["/tmp/it's/nvim.1.0"])
        XCTAssertEqual(command, """
        '/opt/homebrew/bin/nvim' --server '/tmp/it'\\''s/nvim.1.0' --remote-expr \
        'execute("if get(g:, \\"colors_name\\", \\"\\") ==# \\"vibeshed\\" | colorscheme vibeshed | endif")' \
        >/dev/null 2>&1 &
        wait
        """)
    }

    func testFindsServerSocketsAndConfigReference() throws {
        // Unix socket paths are limited to ~104 bytes, so stay short.
        let root = "/tmp/vs-nvim-\(getpid())"
        try FileManager.default.createDirectory(atPath: "\(root)/abc123", withIntermediateDirectories: true)
        defer { try? FileManager.default.removeItem(atPath: root) }
        let socketPath = "\(root)/abc123/nvim.42.0"
        let socket = try Self.bindSocket(socketPath)
        defer { close(socket) }
        FileManager.default.createFile(atPath: "\(root)/nvim.not-a-socket", contents: Data())

        XCTAssertEqual(NeovimTarget.serverSockets(in: [root, "\(root)/missing"]), [ThemeFiles.resolved(socketPath)])

        let config = "\(root)/config"
        try FileManager.default.createDirectory(atPath: "\(config)/colors", withIntermediateDirectories: true)
        try "vim.cmd('colorscheme vibeshed')"
            .write(toFile: "\(config)/colors/vibeshed.lua", atomically: true, encoding: .utf8)
        XCTAssertFalse(NeovimTarget.configSelectsScheme(in: config), "the generated scheme itself doesn't count")
        try FileManager.default.createDirectory(atPath: "\(config)/lua/plugins", withIntermediateDirectories: true)
        try "return { { \"LazyVim/LazyVim\", opts = { colorscheme = \"vibeshed\" } } }"
            .write(toFile: "\(config)/lua/plugins/theme.lua", atomically: true, encoding: .utf8)
        XCTAssertTrue(NeovimTarget.configSelectsScheme(in: config))
    }

    private static func bindSocket(_ path: String) throws -> Int32 {
        let descriptor = socket(AF_UNIX, SOCK_STREAM, 0)
        var address = sockaddr_un()
        address.sun_family = sa_family_t(AF_UNIX)
        withUnsafeMutableBytes(of: &address.sun_path) { buffer in
            path.utf8CString.withUnsafeBytes { buffer.copyMemory(from: $0) }
        }
        let result = withUnsafePointer(to: &address) {
            $0.withMemoryRebound(to: sockaddr.self, capacity: 1) {
                Darwin.bind(descriptor, $0, socklen_t(MemoryLayout<sockaddr_un>.size))
            }
        }
        guard result == 0 else { throw POSIXError(.EADDRINUSE) }
        return descriptor
    }
}
